// Copyright 2026 Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// File auto-generated by Padrick 0.3.6
package pkg_internal_hyperbus_padframe_topr;


  // Indices definitions

  // Dynamic Pad  instance index
endpackage : pkg_internal_hyperbus_padframe_topr
