
// File auto-generated by Padrick unknown
module astral_padframe_botl_pads
  import pkg_astral_padframe::*;
  import pkg_internal_astral_padframe_botl::*;
(
  output pad_domain_botl_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  pad_domain_botl_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
 // Dynamic Pad control signals, these signals are controlled by the multiplexer in the correpsongin pad_controller module
  // Landing Pads
  inout wire logic pad_config_tc_pad_internal_signals_0,
  inout wire logic pad_config_tc_pad_internal_signals_1,
  inout wire logic pad_config_tc_pad_internal_signals_2,
  inout wire logic pad_config_tc_pad_internal_signals_3,
  inout wire logic pad_ot_boot_mode_pad,
  inout wire logic pad_jtag_ot_tclk_pad,
  inout wire logic pad_jtag_ot_trst_n_pad,
  inout wire logic pad_jtag_ot_tms_pad,
  inout wire logic pad_jtag_ot_tdi_pad,
  inout wire logic pad_jtag_ot_tdo_pad,
  inout wire logic pad_ot_uart_tx_pad,
  inout wire logic pad_ot_uart_rx_pad,
  inout wire logic pad_spih_sck_pad,
  inout wire logic pad_spih_csb_pad,
  inout wire logic pad_spih_sd_0_pad,
  inout wire logic pad_spih_sd_1_pad,
  inout wire logic pad_spih_sd_2_pad,
  inout wire logic pad_spih_sd_3_pad,
  inout wire logic pad_gpio_2_pad,
  inout wire logic pad_gpio_3_pad,
  inout wire logic pad_spih_ot_sd_1_pad,
  inout wire logic pad_spih_ot_sd_2_pad,
  inout wire logic pad_spih_ot_sd_3_pad,
  inout wire logic pad_ref_clk_pad,
  inout wire logic pad_fll_host_pad,
  inout wire logic pad_fll_secd_pad,
  inout wire logic pad_fll_bypass_pad,
  inout wire logic pad_pwr_on_rst_n_pad,
  inout wire logic pad_boot_mode_0_pad,
  inout wire logic pad_boot_mode_1_pad,
  inout wire logic pad_secure_boot_pad,
  inout wire logic pad_jtag_tclk_pad,
  inout wire logic pad_jtag_trst_n_pad,
  inout wire logic pad_jtag_tms_pad,
  inout wire logic pad_jtag_tdi_pad,
  inout wire logic pad_jtag_tdo_pad,
  inout wire logic pad_uart_tx_pad,
  inout wire logic pad_uart_rx_pad,
  inout wire logic pad_gpio_0_pad,
  inout wire logic pad_gpio_1_pad,
  inout wire logic pad_spih_ot_sck_pad,
  inout wire logic pad_spih_ot_csb_pad,
  inout wire logic pad_spih_ot_sd_0_pad,
  inout wire logic pad_hyper_1_cs_0_n_pad,
  inout wire logic pad_hyper_1_cs_1_n_pad,
  inout wire logic pad_hyper_1_ck_pad,
  inout wire logic pad_hyper_1_ck_n_pad,
  inout wire logic pad_hyper_1_rwds_pad,
  inout wire logic pad_hyper_1_reset_n_pad,
  inout wire logic pad_hyper_1_dq_0_pad,
  inout wire logic pad_hyper_1_dq_1_pad,
  inout wire logic pad_hyper_1_dq_2_pad,
  inout wire logic pad_hyper_1_dq_3_pad,
  inout wire logic pad_hyper_1_dq_4_pad,
  inout wire logic pad_hyper_1_dq_5_pad,
  inout wire logic pad_hyper_1_dq_6_pad,
  inout wire logic pad_hyper_1_dq_7_pad,
  inout wire logic pad_hyper_0_cs_0_n_pad,
  inout wire logic pad_hyper_0_cs_1_n_pad,
  inout wire logic pad_hyper_0_ck_pad,
  inout wire logic pad_hyper_0_ck_n_pad,
  inout wire logic pad_hyper_0_rwds_pad,
  inout wire logic pad_hyper_0_reset_n_pad,
  inout wire logic pad_hyper_0_dq_0_pad,
  inout wire logic pad_hyper_0_dq_1_pad,
  inout wire logic pad_hyper_0_dq_2_pad,
  inout wire logic pad_hyper_0_dq_3_pad,
  inout wire logic pad_hyper_0_dq_4_pad,
  inout wire logic pad_hyper_0_dq_5_pad,
  inout wire logic pad_hyper_0_dq_6_pad,
  inout wire logic pad_hyper_0_dq_7_pad
  );

   // Pad instantiations
   localparam tc_pad_pkg::tc_pad_config_t gf22_invecas_tc_pad_config = '{
      1'b1,   //av_bidir_cell
      1'b0,   //av_in_cell
      1'b0,   //av_out_cell
      1'b1,   //in_en_ah
      1'b1,   //in_en_latch
      1'b1,   //out_en_ah
      1'b1,   //pu_en_ah
      1'b1,   //pd_en_ah
      1'b1,   //pu_pd_both_en
      1'b1,   //st_en_ah
      1'b1,   //rt_en_ah
      2,      //ds_w
      3       //n_int
  };
  
  wire io_pad_retcin;
  assign io_pad_retcin = 1'b0;
  `define io_pad_internals {pad_config_tc_pad_internal_signals_3, pad_config_tc_pad_internal_signals_2, pad_config_tc_pad_internal_signals_1, pad_config_tc_pad_internal_signals_0}
   tc_pad_corner #( .tc_pad_config ( gf22_invecas_tc_pad_config ) ) i_corner_0 ( .int_io ( `io_pad_internals ) );
   tc_pad_corner #( .tc_pad_config ( gf22_invecas_tc_pad_config ) ) i_corner_1 ( .int_io ( `io_pad_internals ) );
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_south (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_0_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_1_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_ot_boot_mode (
    .pad_io           ( pad_ot_boot_mode_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.ot_boot_mode_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_ot_tclk (
    .pad_io           ( pad_jtag_ot_tclk_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_ot_tclk_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_ot_trst_n (
    .pad_io           ( pad_jtag_ot_trst_n_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_ot_trst_ni   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_ot_tms (
    .pad_io           ( pad_jtag_ot_tms_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_ot_tms_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_ot_tdi (
    .pad_io           ( pad_jtag_ot_tdi_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_ot_tdi_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_ot_tdo (
    .pad_io           ( pad_jtag_ot_tdo_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.jtag_ot_tdo_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_ot_uart_tx (
    .pad_io           ( pad_ot_uart_tx_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.ot_uart_tx_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_ot_uart_rx (
    .pad_io           ( pad_ot_uart_rx_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.ot_uart_rx_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_sck (
    .pad_io           ( pad_spih_sck_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_sck_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_csb (
    .pad_io           ( pad_spih_csb_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_csb_o_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_sd_0 (
    .pad_io           ( pad_spih_sd_0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_sd_i_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_sd_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_sd_o_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_sd_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_sd_1 (
    .pad_io           ( pad_spih_sd_1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_sd_i_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_sd_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_sd_o_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_sd_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_sd_2 (
    .pad_io           ( pad_spih_sd_2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_sd_i_2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_sd_oen_i_2       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_sd_o_2       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_sd_oen_i_2      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_sd_3 (
    .pad_io           ( pad_spih_sd_3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_sd_i_3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_sd_oen_i_3       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_sd_o_3       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_sd_oen_i_3      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_gpio_2 (
    .pad_io           ( pad_gpio_2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.gpio_v_i_2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.gpio_v_oen_i_2       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.gpio_v_o_2       ),
    .output_en_i      ( static_connection_signals_soc2pad.gpio_v_oen_i_2      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_gpio_3 (
    .pad_io           ( pad_gpio_3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.gpio_v_i_3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.gpio_v_oen_i_3       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.gpio_v_o_3       ),
    .output_en_i      ( static_connection_signals_soc2pad.gpio_v_oen_i_3      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_sd_1 (
    .pad_io           ( pad_spih_ot_sd_1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_ot_sd_i_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_ot_sd_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_sd_o_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_ot_sd_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_sd_2 (
    .pad_io           ( pad_spih_ot_sd_2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_ot_sd_i_2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_ot_sd_oen_i_2       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_sd_o_2       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_ot_sd_oen_i_2      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_sd_3 (
    .pad_io           ( pad_spih_ot_sd_3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_ot_sd_i_3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_ot_sd_oen_i_3       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_sd_o_3       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_ot_sd_oen_i_3      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_west (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_0_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_1_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_ref_clk (
    .pad_io           ( pad_ref_clk_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.ref_clk_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_fll_host (
    .pad_io           ( pad_fll_host_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.fll_host_clk_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_fll_secd (
    .pad_io           ( pad_fll_secd_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.fll_secd_clk_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_fll_bypass (
    .pad_io           ( pad_fll_bypass_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.fll_bypass_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_on_rst_n (
    .pad_io           ( pad_pwr_on_rst_n_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.pwr_on_rst_ni   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_boot_mode_0 (
    .pad_io           ( pad_boot_mode_0_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.boot_mode_i_0   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_boot_mode_1 (
    .pad_io           ( pad_boot_mode_1_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.boot_mode_i_1   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_secure_boot (
    .pad_io           ( pad_secure_boot_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.secure_boot_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_tclk (
    .pad_io           ( pad_jtag_tclk_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_tclk_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_trst_n (
    .pad_io           ( pad_jtag_trst_n_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_trst_ni   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_tms (
    .pad_io           ( pad_jtag_tms_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_tms_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_tdi (
    .pad_io           ( pad_jtag_tdi_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.jtag_tdi_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_jtag_tdo (
    .pad_io           ( pad_jtag_tdo_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.jtag_tdo_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_uart_tx (
    .pad_io           ( pad_uart_tx_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.uart_tx_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_uart_rx (
    .pad_io           ( pad_uart_rx_pad        ),
    .pad2chip_o       ( static_connection_signals_pad2soc.uart_rx_i   ),
    .input_en_i       ( 1'b1   ),
    .pu_en_i          ( 1'b0      ),
    .pd_en_i          ( 1'b0      ),
    .schmitt_en_i     ( 1'b0 ),
    .nand_in_i        ( 1'b0    ),
    .nand_out_o       (    ),
    .chip2pad_i       ( 1'b0                  ),
    .output_en_i      ( 1'b0                  ),
    .slew_en_i        ( 1'b0                  ),
    .drive_strength_i ( 2'b00                 ),
    .int_io           ( `io_pad_internals     )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_gpio_0 (
    .pad_io           ( pad_gpio_0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.gpio_v_i_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.gpio_v_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.gpio_v_o_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.gpio_v_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_gpio_1 (
    .pad_io           ( pad_gpio_1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.gpio_v_i_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.gpio_v_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.gpio_v_o_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.gpio_v_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_sck (
    .pad_io           ( pad_spih_ot_sck_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_sck_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_csb (
    .pad_io           ( pad_spih_ot_csb_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_csb_o       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_spih_ot_sd_0 (
    .pad_io           ( pad_spih_ot_sd_0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.spih_ot_sd_i_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.spih_ot_sd_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.spih_ot_sd_o_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.spih_ot_sd_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_corner #( .tc_pad_config ( gf22_invecas_tc_pad_config ) ) i_corner_2 ( .int_io ( `io_pad_internals ) );
   tc_pad_corner #( .tc_pad_config ( gf22_invecas_tc_pad_config ) ) i_corner_3 ( .int_io ( `io_pad_internals ) );
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_north (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_3_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_4_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_3_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_4_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_3_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_4_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_5_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_2_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_3_v (
    .int_io ( `io_pad_internals )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_cs_0_n (
    .pad_io           ( pad_hyper_1_cs_0_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_cs_no_1_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_cs_1_n (
    .pad_io           ( pad_hyper_1_cs_1_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_cs_no_1_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_ck (
    .pad_io           ( pad_hyper_1_ck_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_ck_o_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_ck_n (
    .pad_io           ( pad_hyper_1_ck_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_ck_no_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_rwds (
    .pad_io           ( pad_hyper_1_rwds_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_rwds_i_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_rwds_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_rwds_o_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_rwds_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_reset_n (
    .pad_io           ( pad_hyper_1_reset_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_reset_no_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );   
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_0 (
    .pad_io           ( pad_hyper_1_dq_0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_1 (
    .pad_io           ( pad_hyper_1_dq_1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_2 (
    .pad_io           ( pad_hyper_1_dq_2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_2       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_3 (
    .pad_io           ( pad_hyper_1_dq_3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_3       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_4 (
    .pad_io           ( pad_hyper_1_dq_4_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_4       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_4       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_5 (
    .pad_io           ( pad_hyper_1_dq_5_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_5       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_5       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_6 (
    .pad_io           ( pad_hyper_1_dq_6_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_6       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_6       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::V              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_1_dq_7 (
    .pad_io           ( pad_hyper_1_dq_7_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_1_7       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_1       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_1_7       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_pwr_mng #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_pwr_mng_east (
    .ret_en_i ( io_pad_retcin     ),
    .int_io   ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_3_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_io_4_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_3_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_io #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_io_4_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_3_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vdd_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vdd_core_4_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_2_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_vss_core #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_vss_core_3_h (
    .int_io ( `io_pad_internals )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_cs_0_n (
    .pad_io           ( pad_hyper_0_cs_0_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_cs_no_0_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_cs_1_n (
    .pad_io           ( pad_hyper_0_cs_1_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_cs_no_0_1       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_ck (
    .pad_io           ( pad_hyper_0_ck_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_ck_o_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_ck_n (
    .pad_io           ( pad_hyper_0_ck_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_ck_no_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_rwds (
    .pad_io           ( pad_hyper_0_rwds_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_rwds_i_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_rwds_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_rwds_o_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_rwds_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_reset_n (
    .pad_io           ( pad_hyper_0_reset_n_pad            ),
    .pad2chip_o       (                           ),
    .input_en_i       ( 1'b0                      ),
    .pu_en_i          ( 1'b0                      ),
    .pd_en_i          ( 1'b0                      ),
    .schmitt_en_i     ( 1'b0                      ),
    .nand_in_i        ( 1'b0                      ),
    .nand_out_o       (                           ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_reset_no_0       ),
    .output_en_i      ( 1'b1      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );    
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_0 (
    .pad_io           ( pad_hyper_0_dq_0_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_0       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_0       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_1 (
    .pad_io           ( pad_hyper_0_dq_1_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_1       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_1       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_2 (
    .pad_io           ( pad_hyper_0_dq_2_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_2       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_2       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_3 (
    .pad_io           ( pad_hyper_0_dq_3_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_3       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_3       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_4 (
    .pad_io           ( pad_hyper_0_dq_4_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_4       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_4       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_5 (
    .pad_io           ( pad_hyper_0_dq_5_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_5       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_5       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_6 (
    .pad_io           ( pad_hyper_0_dq_6_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_6       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_6       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );
   tc_pad_bidir #(
    .tc_pad_orientation ( tc_pad_pkg::H              ),
    .tc_pad_config      ( gf22_invecas_tc_pad_config )
  ) i_hyper_0_dq_7 (
    .pad_io           ( pad_hyper_0_dq_7_pad            ),
    .pad2chip_o       ( static_connection_signals_pad2soc.hyper_dq_i_0_7       ),
    .input_en_i       ( ~static_connection_signals_soc2pad.hyper_dq_oen_i_0       ),
    .pu_en_i          ( 1'b0          ),
    .pd_en_i          ( 1'b0          ),
    .schmitt_en_i     ( 1'b0     ),
    .nand_in_i        ( 1'b0        ),
    .nand_out_o       (        ),
    .chip2pad_i       ( static_connection_signals_soc2pad.hyper_dq_o_0_7       ),
    .output_en_i      ( static_connection_signals_soc2pad.hyper_dq_oen_i_0      ),
    .slew_en_i        ( 1'b0        ),
    .drive_strength_i ( 2'b00 ),
    .int_io           ( `io_pad_internals         )
  );

endmodule : astral_padframe_botl_pads
