
// File auto-generated by Padrick unknown
module astral_padframe_periph_pads
  import pkg_astral_padframe::*;
  import pkg_internal_astral_padframe_periph::*;
(
  output pad_domain_periph_static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  pad_domain_periph_static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
 // Dynamic Pad control signals, these signals are controlled by the multiplexer in the correpsongin pad_controller module
  input mux_to_pads_t mux_to_pads_i,
  output pads_to_mux_t pads_to_mux_o,
  // Landing Pads
  inout wire logic pad_ref_clk_pad_i,
  inout wire logic pad_ref_clk_pad_o,
  inout wire logic pad_fll_bypass_pad,
  inout wire logic pad_pwr_on_rst_n_pad,
  inout wire logic pad_test_mode_pad,
  inout wire logic pad_boot_mode_0_pad,
  inout wire logic pad_boot_mode_1_pad,
  inout wire logic pad_secure_boot_pad,
  inout wire logic pad_jtag_tclk_pad,
  inout wire logic pad_jtag_trst_n_pad,
  inout wire logic pad_jtag_tms_pad,
  inout wire logic pad_jtag_tdi_pad,
  inout wire logic pad_jtag_tdo_pad,
  inout wire logic pad_jtag_ot_tclk_pad,
  inout wire logic pad_jtag_ot_trst_ni_pad,
  inout wire logic pad_jtag_ot_tms_pad,
  inout wire logic pad_jtag_ot_tdi_pad,
  inout wire logic pad_jtag_ot_tdo_pad,
  inout wire logic pad_hyper_cs_0_n_pad,
  inout wire logic pad_hyper_cs_1_n_pad,
  inout wire logic pad_hyper_ck_pad,
  inout wire logic pad_hyper_ck_n_pad,
  inout wire logic pad_hyper_rwds_pad,
  inout wire logic pad_hyper_dq_0_pad,
  inout wire logic pad_hyper_dq_1_pad,
  inout wire logic pad_hyper_dq_2_pad,
  inout wire logic pad_hyper_dq_3_pad,
  inout wire logic pad_hyper_dq_4_pad,
  inout wire logic pad_hyper_dq_5_pad,
  inout wire logic pad_hyper_dq_6_pad,
  inout wire logic pad_hyper_dq_7_pad,
  inout wire logic pad_hyper_reset_n_pad,
  inout wire logic pad_spw_data_in_pad,
  inout wire logic pad_spw_strb_in_pad,
  inout wire logic pad_spw_data_out_pad,
  inout wire logic pad_spw_strb_out_pad,
  inout wire logic pad_uart_tx_out_pad,
  inout wire logic pad_uart_rx_in_pad,
  inout wire logic pad_muxed_v_00_pad,
  inout wire logic pad_muxed_v_01_pad,
  inout wire logic pad_muxed_v_02_pad,
  inout wire logic pad_muxed_v_03_pad,
  inout wire logic pad_muxed_v_04_pad,
  inout wire logic pad_muxed_v_05_pad,
  inout wire logic pad_muxed_v_06_pad,
  inout wire logic pad_muxed_v_07_pad,
  inout wire logic pad_muxed_v_08_pad,
  inout wire logic pad_muxed_v_09_pad,
  inout wire logic pad_muxed_v_10_pad,
  inout wire logic pad_muxed_v_11_pad,
  inout wire logic pad_muxed_v_12_pad,
  inout wire logic pad_muxed_v_13_pad,
  inout wire logic pad_muxed_v_14_pad,
  inout wire logic pad_muxed_v_15_pad,
  inout wire logic pad_muxed_v_16_pad,
  inout wire logic pad_muxed_v_17_pad,
  inout wire logic pad_muxed_v_18_pad,
  inout wire logic pad_muxed_v_19_pad,
  inout wire logic pad_muxed_v_20_pad,
  inout wire logic pad_muxed_v_21_pad
  );

   // Pad instantiations
   wire io_pads_rto;
  wire io_pads_sns;
  
  PDVDDTIE_18_18_NT_DR_H i_pad_tie_io (
    .SNS( io_pads_sns ),
    .RTO( io_pads_rto )
  );
   PDVDD_18_18_NT_DR_H i_pad_dvdd_io_h_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_H i_pad_dvdd_io_h_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_4 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVDD_18_18_NT_DR_V i_pad_dvdd_io_v_5 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_H i_pad_dvss_io_h_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_H i_pad_dvss_io_h_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_4 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PDVSS_18_18_NT_DR_V i_pad_dvss_io_v_5 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_H i_pad_vdd_core_h_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_H i_pad_vdd_core_h_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_H i_pad_vdd_core_h_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_H i_pad_vdd_core_h_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_4 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVDD_08_08_NT_DR_V i_pad_vdd_core_v_5 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_H i_pad_vss_core_h_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_H i_pad_vss_core_h_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_H i_pad_vss_core_h_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_H i_pad_vss_core_h_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_4 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PVSS_08_08_NT_DR_V i_pad_vss_core_v_5 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PCORNER_18_18_NT_DR i_pad_corner_0 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PCORNER_18_18_NT_DR i_pad_corner_1 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PCORNER_18_18_NT_DR i_pad_corner_2 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   PCORNER_18_18_NT_DR i_pad_corner_3 ( .SNS( io_pads_sns ), .RTO( io_pads_rto ) );
   (* dont_touch *)
  POSCP_18_18_NT_DR_H i_ref_clk (
    .CK     ( static_connection_signals_pad2soc.ref_clk_i ),
    .CK_IOV (  ),
    .PO     (  ),
    .PADO   ( pad_ref_clk_pad_o ),
    .E0     ( 1'b1 ),
    .PADI   ( pad_ref_clk_pad_i ),
    .POE    ( 1'b0 ),
    .RTO    ( io_pads_rto ),
    .SF0    ( 1'b0 ),
    .SF1    ( 1'b0 ),
    .SNS    ( io_pads_sns ),
    .SP     ( 1'b0 ),
    .TE     ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_fll_bypass (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.fll_bypass_i ),
    .PAD ( pad_fll_bypass_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_pwr_on_rst_n (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.pwr_on_rst_ni ),
    .PAD ( pad_pwr_on_rst_n_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_test_mode (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.test_mode_i ),
    .PAD ( pad_test_mode_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_boot_mode_0 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.boot_mode_0_i ),
    .PAD ( pad_boot_mode_0_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_boot_mode_1 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.boot_mode_1_i ),
    .PAD ( pad_boot_mode_1_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_secure_boot (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.secure_boot_i ),
    .PAD ( pad_secure_boot_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_tclk (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_tclk_i ),
    .PAD ( pad_jtag_tclk_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_trst_n (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_trst_ni ),
    .PAD ( pad_jtag_trst_n_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_tms (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_tms_i ),
    .PAD ( pad_jtag_tms_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_tdi (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_tdi_i ),
    .PAD ( pad_jtag_tdi_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_tdo (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_jtag_tdo_pad ),
    .A   ( static_connection_signals_soc2pad.jtag_tdo_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_ot_tclk (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_ot_tclk_i ),
    .PAD ( pad_jtag_ot_tclk_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_ot_trst_ni (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_ot_trst_ni ),
    .PAD ( pad_jtag_ot_trst_ni_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_ot_tms (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_ot_tms_i ),
    .PAD ( pad_jtag_ot_tms_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_ot_tdi (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.jtag_ot_tdi_i ),
    .PAD ( pad_jtag_ot_tdi_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_jtag_ot_tdo (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_jtag_ot_tdo_pad ),
    .A   ( static_connection_signals_soc2pad.jtag_ot_tdo_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_cs_0_n (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_hyper_cs_0_n_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_cs_0_no ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_cs_1_n (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_hyper_cs_1_n_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_cs_1_no ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_ck (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_hyper_ck_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_ck_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_ck_n (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_hyper_ck_n_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_ck_no ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_rwds (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_rwds_i ),
    .PAD ( pad_hyper_rwds_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_rwds_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_rwds_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_rwds_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_0 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_0_i ),
    .PAD ( pad_hyper_dq_0_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_0_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_1 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_1_i ),
    .PAD ( pad_hyper_dq_1_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_1_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_2 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_2_i ),
    .PAD ( pad_hyper_dq_2_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_2_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_3 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_3_i ),
    .PAD ( pad_hyper_dq_3_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_3_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_4 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_4_i ),
    .PAD ( pad_hyper_dq_4_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_4_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_5 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_5_i ),
    .PAD ( pad_hyper_dq_5_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_5_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_6 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_6_i ),
    .PAD ( pad_hyper_dq_6_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_6_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_dq_7 (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.hyper_dq_7_i ),
    .PAD ( pad_hyper_dq_7_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_dq_7_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( ~static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .IS  ( 1'b0 ),
    .OE  ( static_connection_signals_soc2pad.hyper_dq_oen_i ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_hyper_reset_n (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_hyper_reset_n_pad ),
    .A   ( static_connection_signals_soc2pad.hyper_reset_no ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_spw_data_in (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.spw_data_i ),
    .PAD ( pad_spw_data_in_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_spw_strb_in (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.spw_srtb_i ),
    .PAD ( pad_spw_strb_in_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_spw_data_out (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_spw_data_out_pad ),
    .A   ( static_connection_signals_soc2pad.spw_data_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_spw_strb_out (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_spw_strb_out_pad ),
    .A   ( static_connection_signals_soc2pad.spw_srtb_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_uart_tx_out (
    .PO  (  ),
    .Y   (  ),
    .PAD ( pad_uart_tx_out_pad ),
    .A   ( static_connection_signals_soc2pad.uart_tx_o ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b0 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b1 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_H i_uart_rx_in (
    .PO  (  ),
    .Y   ( static_connection_signals_pad2soc.uart_rx_i ),
    .PAD ( pad_uart_rx_in_pad ),
    .A   ( 1'b0 ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( 1'b1 ),
    .IS  ( 1'b0 ),
    .OE  ( 1'b0 ),
    .PE  ( 1'b0 ),
    .POE ( 1'b0 ),
    .PS  ( 1'b0 ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_00 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_00.pad2chip ),
    .PAD ( pad_muxed_v_00_pad ),
    .A   ( mux_to_pads_i.muxed_v_00.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_00.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_00.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_00.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_00.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_01 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_01.pad2chip ),
    .PAD ( pad_muxed_v_01_pad ),
    .A   ( mux_to_pads_i.muxed_v_01.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_01.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_01.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_01.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_01.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_02 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_02.pad2chip ),
    .PAD ( pad_muxed_v_02_pad ),
    .A   ( mux_to_pads_i.muxed_v_02.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_02.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_02.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_02.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_02.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_03 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_03.pad2chip ),
    .PAD ( pad_muxed_v_03_pad ),
    .A   ( mux_to_pads_i.muxed_v_03.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_03.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_03.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_03.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_03.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_04 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_04.pad2chip ),
    .PAD ( pad_muxed_v_04_pad ),
    .A   ( mux_to_pads_i.muxed_v_04.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_04.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_04.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_04.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_04.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_05 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_05.pad2chip ),
    .PAD ( pad_muxed_v_05_pad ),
    .A   ( mux_to_pads_i.muxed_v_05.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_05.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_05.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_05.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_05.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_06 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_06.pad2chip ),
    .PAD ( pad_muxed_v_06_pad ),
    .A   ( mux_to_pads_i.muxed_v_06.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_06.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_06.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_06.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_06.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_07 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_07.pad2chip ),
    .PAD ( pad_muxed_v_07_pad ),
    .A   ( mux_to_pads_i.muxed_v_07.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_07.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_07.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_07.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_07.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_08 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_08.pad2chip ),
    .PAD ( pad_muxed_v_08_pad ),
    .A   ( mux_to_pads_i.muxed_v_08.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_08.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_08.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_08.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_08.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_09 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_09.pad2chip ),
    .PAD ( pad_muxed_v_09_pad ),
    .A   ( mux_to_pads_i.muxed_v_09.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_09.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_09.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_09.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_09.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_10 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_10.pad2chip ),
    .PAD ( pad_muxed_v_10_pad ),
    .A   ( mux_to_pads_i.muxed_v_10.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_10.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_10.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_10.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_10.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_11 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_11.pad2chip ),
    .PAD ( pad_muxed_v_11_pad ),
    .A   ( mux_to_pads_i.muxed_v_11.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_11.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_11.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_11.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_11.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_12 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_12.pad2chip ),
    .PAD ( pad_muxed_v_12_pad ),
    .A   ( mux_to_pads_i.muxed_v_12.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_12.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_12.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_12.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_12.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_13 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_13.pad2chip ),
    .PAD ( pad_muxed_v_13_pad ),
    .A   ( mux_to_pads_i.muxed_v_13.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_13.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_13.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_13.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_13.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_14 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_14.pad2chip ),
    .PAD ( pad_muxed_v_14_pad ),
    .A   ( mux_to_pads_i.muxed_v_14.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_14.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_14.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_14.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_14.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_15 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_15.pad2chip ),
    .PAD ( pad_muxed_v_15_pad ),
    .A   ( mux_to_pads_i.muxed_v_15.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_15.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_15.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_15.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_15.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_16 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_16.pad2chip ),
    .PAD ( pad_muxed_v_16_pad ),
    .A   ( mux_to_pads_i.muxed_v_16.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_16.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_16.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_16.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_16.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_17 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_17.pad2chip ),
    .PAD ( pad_muxed_v_17_pad ),
    .A   ( mux_to_pads_i.muxed_v_17.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_17.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_17.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_17.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_17.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_18 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_18.pad2chip ),
    .PAD ( pad_muxed_v_18_pad ),
    .A   ( mux_to_pads_i.muxed_v_18.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_18.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_18.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_18.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_18.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_19 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_19.pad2chip ),
    .PAD ( pad_muxed_v_19_pad ),
    .A   ( mux_to_pads_i.muxed_v_19.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_19.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_19.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_19.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_19.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_20 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_20.pad2chip ),
    .PAD ( pad_muxed_v_20_pad ),
    .A   ( mux_to_pads_i.muxed_v_20.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_20.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_20.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_20.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_20.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );
   (* dont_touch *)
  PBIDIR_18_18_NT_DR_V i_muxed_v_21 (
    .PO  (  ),
    .Y   ( pads_to_mux_o.muxed_v_21.pad2chip ),
    .PAD ( pad_muxed_v_21_pad ),
    .A   ( mux_to_pads_i.muxed_v_21.chip2pad ),
    .DS0 ( 1'b0 ),
    .DS1 ( 1'b0 ),
    .IE  ( mux_to_pads_i.muxed_v_21.input_en ),
    .IS  ( 1'b0 ),
    .OE  ( mux_to_pads_i.muxed_v_21.output_en ),
    .PE  ( mux_to_pads_i.muxed_v_21.pull_en ),
    .POE ( 1'b0 ),
    .PS  ( mux_to_pads_i.muxed_v_21.pull_sel ),
    .RTO ( io_pads_rto ),
    .SNS ( io_pads_sns ),
    .SR  ( 1'b0 )
  );

endmodule : astral_padframe_periph_pads
