
// File auto-generated by Padrick unknown
module astral_padframe
  import pkg_astral_padframe::*;
#(
  parameter int unsigned   AW = 32,
  parameter int unsigned   DW = 32,
  parameter type req_t = logic, // reg_interface request type
  parameter type resp_t = logic, // reg_interface response type
  parameter logic [DW-1:0] DecodeErrRespData = 32'hdeadda7a
)(
  input logic                                clk_i,
  input logic                                rst_ni,
  output static_connection_signals_pad2soc_t static_connection_signals_pad2soc,
  input  static_connection_signals_soc2pad_t static_connection_signals_soc2pad,
  // Landing Pads
  inout wire logic                           pad_botl_config_tc_pad_internal_signals_0,
  inout wire logic                           pad_botl_config_tc_pad_internal_signals_1,
  inout wire logic                           pad_botl_config_tc_pad_internal_signals_2,
  inout wire logic                           pad_botl_config_tc_pad_internal_signals_3,
  inout wire logic                           pad_botl_ot_boot_mode_pad,
  inout wire logic                           pad_botl_jtag_ot_tclk_pad,
  inout wire logic                           pad_botl_jtag_ot_trst_n_pad,
  inout wire logic                           pad_botl_jtag_ot_tms_pad,
  inout wire logic                           pad_botl_jtag_ot_tdi_pad,
  inout wire logic                           pad_botl_jtag_ot_tdo_pad,
  inout wire logic                           pad_botl_ot_uart_tx_pad,
  inout wire logic                           pad_botl_ot_uart_rx_pad,
  inout wire logic                           pad_botl_spih_sck_pad,
  inout wire logic                           pad_botl_spih_csb_pad,
  inout wire logic                           pad_botl_spih_sd_0_pad,
  inout wire logic                           pad_botl_spih_sd_1_pad,
  inout wire logic                           pad_botl_spih_sd_2_pad,
  inout wire logic                           pad_botl_spih_sd_3_pad,
  inout wire logic                           pad_botl_gpio_2_pad,
  inout wire logic                           pad_botl_gpio_3_pad,
  inout wire logic                           pad_botl_spih_ot_sd_1_pad,
  inout wire logic                           pad_botl_spih_ot_sd_2_pad,
  inout wire logic                           pad_botl_spih_ot_sd_3_pad,
  inout wire logic                           pad_botl_ref_clk_pad,
  inout wire logic                           pad_botl_fll_host_pad,
  inout wire logic                           pad_botl_fll_secd_pad,
  inout wire logic                           pad_botl_fll_bypass_pad,
  inout wire logic                           pad_botl_pwr_on_rst_n_pad,
  inout wire logic                           pad_botl_boot_mode_0_pad,
  inout wire logic                           pad_botl_boot_mode_1_pad,
  inout wire logic                           pad_botl_secure_boot_pad,
  inout wire logic                           pad_botl_jtag_tclk_pad,
  inout wire logic                           pad_botl_jtag_trst_n_pad,
  inout wire logic                           pad_botl_jtag_tms_pad,
  inout wire logic                           pad_botl_jtag_tdi_pad,
  inout wire logic                           pad_botl_jtag_tdo_pad,
  inout wire logic                           pad_botl_uart_tx_pad,
  inout wire logic                           pad_botl_uart_rx_pad,
  inout wire logic                           pad_botl_gpio_0_pad,
  inout wire logic                           pad_botl_gpio_1_pad,
  inout wire logic                           pad_botl_spih_ot_sck_pad,
  inout wire logic                           pad_botl_spih_ot_csb_pad,
  inout wire logic                           pad_botl_spih_ot_sd_0_pad,
  inout wire logic                           pad_botl_hyper_1_cs_0_n_pad,
  inout wire logic                           pad_botl_hyper_1_cs_1_n_pad,
  inout wire logic                           pad_botl_hyper_1_ck_pad,
  inout wire logic                           pad_botl_hyper_1_ck_n_pad,
  inout wire logic                           pad_botl_hyper_1_rwds_pad,
  inout wire logic                           pad_botl_hyper_1_reset_n_pad,
  inout wire logic                           pad_botl_hyper_1_dq_0_pad,
  inout wire logic                           pad_botl_hyper_1_dq_1_pad,
  inout wire logic                           pad_botl_hyper_1_dq_2_pad,
  inout wire logic                           pad_botl_hyper_1_dq_3_pad,
  inout wire logic                           pad_botl_hyper_1_dq_4_pad,
  inout wire logic                           pad_botl_hyper_1_dq_5_pad,
  inout wire logic                           pad_botl_hyper_1_dq_6_pad,
  inout wire logic                           pad_botl_hyper_1_dq_7_pad,
  inout wire logic                           pad_botl_hyper_0_cs_0_n_pad,
  inout wire logic                           pad_botl_hyper_0_cs_1_n_pad,
  inout wire logic                           pad_botl_hyper_0_ck_pad,
  inout wire logic                           pad_botl_hyper_0_ck_n_pad,
  inout wire logic                           pad_botl_hyper_0_rwds_pad,
  inout wire logic                           pad_botl_hyper_0_reset_n_pad,
  inout wire logic                           pad_botl_hyper_0_dq_0_pad,
  inout wire logic                           pad_botl_hyper_0_dq_1_pad,
  inout wire logic                           pad_botl_hyper_0_dq_2_pad,
  inout wire logic                           pad_botl_hyper_0_dq_3_pad,
  inout wire logic                           pad_botl_hyper_0_dq_4_pad,
  inout wire logic                           pad_botl_hyper_0_dq_5_pad,
  inout wire logic                           pad_botl_hyper_0_dq_6_pad,
  inout wire logic                           pad_botl_hyper_0_dq_7_pad,
  // Config Interface
  input req_t                                config_req_i,
  output resp_t                              config_rsp_o
  );


  req_t botl_config_req;
  resp_t botl_config_resp;
  astral_padframe_botl #(
    .req_t(req_t),
    .resp_t(resp_t)
  ) i_botl (
   .clk_i,
   .rst_ni,
   .static_connection_signals_pad2soc(static_connection_signals_pad2soc.botl),
   .static_connection_signals_soc2pad(static_connection_signals_soc2pad.botl),
   .pad_config_tc_pad_internal_signals_0(pad_botl_config_tc_pad_internal_signals_0),
   .pad_config_tc_pad_internal_signals_1(pad_botl_config_tc_pad_internal_signals_1),
   .pad_config_tc_pad_internal_signals_2(pad_botl_config_tc_pad_internal_signals_2),
   .pad_config_tc_pad_internal_signals_3(pad_botl_config_tc_pad_internal_signals_3),
   .pad_ot_boot_mode_pad(pad_botl_ot_boot_mode_pad),
   .pad_jtag_ot_tclk_pad(pad_botl_jtag_ot_tclk_pad),
   .pad_jtag_ot_trst_n_pad(pad_botl_jtag_ot_trst_n_pad),
   .pad_jtag_ot_tms_pad(pad_botl_jtag_ot_tms_pad),
   .pad_jtag_ot_tdi_pad(pad_botl_jtag_ot_tdi_pad),
   .pad_jtag_ot_tdo_pad(pad_botl_jtag_ot_tdo_pad),
   .pad_ot_uart_tx_pad(pad_botl_ot_uart_tx_pad),
   .pad_ot_uart_rx_pad(pad_botl_ot_uart_rx_pad),
   .pad_spih_sck_pad(pad_botl_spih_sck_pad),
   .pad_spih_csb_pad(pad_botl_spih_csb_pad),
   .pad_spih_sd_0_pad(pad_botl_spih_sd_0_pad),
   .pad_spih_sd_1_pad(pad_botl_spih_sd_1_pad),
   .pad_spih_sd_2_pad(pad_botl_spih_sd_2_pad),
   .pad_spih_sd_3_pad(pad_botl_spih_sd_3_pad),
   .pad_gpio_2_pad(pad_botl_gpio_2_pad),
   .pad_gpio_3_pad(pad_botl_gpio_3_pad),
   .pad_spih_ot_sd_1_pad(pad_botl_spih_ot_sd_1_pad),
   .pad_spih_ot_sd_2_pad(pad_botl_spih_ot_sd_2_pad),
   .pad_spih_ot_sd_3_pad(pad_botl_spih_ot_sd_3_pad),
   .pad_ref_clk_pad(pad_botl_ref_clk_pad),
   .pad_fll_host_pad(pad_botl_fll_host_pad),
   .pad_fll_secd_pad(pad_botl_fll_secd_pad),
   .pad_fll_bypass_pad(pad_botl_fll_bypass_pad),
   .pad_pwr_on_rst_n_pad(pad_botl_pwr_on_rst_n_pad),
   .pad_boot_mode_0_pad(pad_botl_boot_mode_0_pad),
   .pad_boot_mode_1_pad(pad_botl_boot_mode_1_pad),
   .pad_secure_boot_pad(pad_botl_secure_boot_pad),
   .pad_jtag_tclk_pad(pad_botl_jtag_tclk_pad),
   .pad_jtag_trst_n_pad(pad_botl_jtag_trst_n_pad),
   .pad_jtag_tms_pad(pad_botl_jtag_tms_pad),
   .pad_jtag_tdi_pad(pad_botl_jtag_tdi_pad),
   .pad_jtag_tdo_pad(pad_botl_jtag_tdo_pad),
   .pad_uart_tx_pad(pad_botl_uart_tx_pad),
   .pad_uart_rx_pad(pad_botl_uart_rx_pad),
   .pad_gpio_0_pad(pad_botl_gpio_0_pad),
   .pad_gpio_1_pad(pad_botl_gpio_1_pad),
   .pad_spih_ot_sck_pad(pad_botl_spih_ot_sck_pad),
   .pad_spih_ot_csb_pad(pad_botl_spih_ot_csb_pad),
   .pad_spih_ot_sd_0_pad(pad_botl_spih_ot_sd_0_pad),
   .pad_hyper_1_cs_0_n_pad(pad_botl_hyper_1_cs_0_n_pad),
   .pad_hyper_1_cs_1_n_pad(pad_botl_hyper_1_cs_1_n_pad),
   .pad_hyper_1_ck_pad(pad_botl_hyper_1_ck_pad),
   .pad_hyper_1_ck_n_pad(pad_botl_hyper_1_ck_n_pad),
   .pad_hyper_1_rwds_pad(pad_botl_hyper_1_rwds_pad),
   .pad_hyper_1_reset_n_pad(pad_botl_hyper_1_reset_n_pad),
   .pad_hyper_1_dq_0_pad(pad_botl_hyper_1_dq_0_pad),
   .pad_hyper_1_dq_1_pad(pad_botl_hyper_1_dq_1_pad),
   .pad_hyper_1_dq_2_pad(pad_botl_hyper_1_dq_2_pad),
   .pad_hyper_1_dq_3_pad(pad_botl_hyper_1_dq_3_pad),
   .pad_hyper_1_dq_4_pad(pad_botl_hyper_1_dq_4_pad),
   .pad_hyper_1_dq_5_pad(pad_botl_hyper_1_dq_5_pad),
   .pad_hyper_1_dq_6_pad(pad_botl_hyper_1_dq_6_pad),
   .pad_hyper_1_dq_7_pad(pad_botl_hyper_1_dq_7_pad),
   .pad_hyper_0_cs_0_n_pad(pad_botl_hyper_0_cs_0_n_pad),
   .pad_hyper_0_cs_1_n_pad(pad_botl_hyper_0_cs_1_n_pad),
   .pad_hyper_0_ck_pad(pad_botl_hyper_0_ck_pad),
   .pad_hyper_0_ck_n_pad(pad_botl_hyper_0_ck_n_pad),
   .pad_hyper_0_rwds_pad(pad_botl_hyper_0_rwds_pad),
   .pad_hyper_0_reset_n_pad(pad_botl_hyper_0_reset_n_pad),
   .pad_hyper_0_dq_0_pad(pad_botl_hyper_0_dq_0_pad),
   .pad_hyper_0_dq_1_pad(pad_botl_hyper_0_dq_1_pad),
   .pad_hyper_0_dq_2_pad(pad_botl_hyper_0_dq_2_pad),
   .pad_hyper_0_dq_3_pad(pad_botl_hyper_0_dq_3_pad),
   .pad_hyper_0_dq_4_pad(pad_botl_hyper_0_dq_4_pad),
   .pad_hyper_0_dq_5_pad(pad_botl_hyper_0_dq_5_pad),
   .pad_hyper_0_dq_6_pad(pad_botl_hyper_0_dq_6_pad),
   .pad_hyper_0_dq_7_pad(pad_botl_hyper_0_dq_7_pad),
   .config_req_i(botl_config_req),
   .config_rsp_o(botl_config_resp)
  );


   localparam int unsigned NUM_PAD_DOMAINS = 1;
   localparam int unsigned REG_ADDR_WIDTH = 3;
   typedef struct packed {
      int unsigned idx;
      logic [REG_ADDR_WIDTH-1:0] start_addr;
      logic [REG_ADDR_WIDTH-1:0] end_addr;
   } addr_rule_t;

   localparam addr_rule_t[NUM_PAD_DOMAINS-1:0] ADDR_DEMUX_RULES = '{
     '{ idx: 0, start_addr: 3'd0,  end_addr: 3'd4}
     };
   logic[$clog2(NUM_PAD_DOMAINS+1)-1:0] pad_domain_sel; // +1 since there is an additional error slave
   addr_decode #(
       .NoIndices(NUM_PAD_DOMAINS+1),
       .NoRules(NUM_PAD_DOMAINS),
       .addr_t(logic[REG_ADDR_WIDTH-1:0]),
       .rule_t(addr_rule_t)
     ) i_addr_decode(
       .addr_i(config_req_i.addr[REG_ADDR_WIDTH-1:0]),
       .addr_map_i(ADDR_DEMUX_RULES),
       .dec_valid_o(),
       .dec_error_o(),
       .idx_o(pad_domain_sel),
       .en_default_idx_i(1'b1),
       .default_idx_i(1'd1) // The last entry is the error slave
     );

     req_t error_slave_req;
     resp_t error_slave_rsp;

     // Config Interface demultiplexing
     reg_demux #(
       .NoPorts(NUM_PAD_DOMAINS+1), //+1 for the error slave
       .req_t(req_t),
       .rsp_t(resp_t)
     ) i_config_demuxer (
       .clk_i,
       .rst_ni,
       .in_select_i(pad_domain_sel),
       .in_req_i(config_req_i),
       .in_rsp_o(config_rsp_o),
       .out_req_o({error_slave_req, botl_config_req}),
       .out_rsp_i({error_slave_rsp, botl_config_resp})
     );

     assign error_slave_rsp.error = 1'b1;
     assign error_slave_rsp.rdata = DecodeErrRespData;
     assign error_slave_rsp.ready = 1'b1;

endmodule
