// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package astral_padframe_periph_config_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 8;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } hw_version;
    struct packed {
      logic [15:0] q;
    } padcount;
  } astral_padframe_periph_config_reg2hw_info_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_00_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_00_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_01_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_01_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_02_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_02_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_03_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_03_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_04_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_04_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_05_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_05_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_06_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_06_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_07_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_07_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_08_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_08_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_09_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_09_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_10_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_10_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_11_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_11_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_12_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_12_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_13_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_13_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_14_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_14_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_15_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_15_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_16_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_16_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_17_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_17_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_18_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_18_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_19_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_19_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_20_cfg_reg_t;

  typedef struct packed {
    logic [2:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_20_mux_sel_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } chip2pad;
    struct packed {
      logic        q;
    } input_en;
    struct packed {
      logic        q;
    } output_en;
    struct packed {
      logic        q;
    } pull_en;
    struct packed {
      logic        q;
    } pull_sel;
  } astral_padframe_periph_config_reg2hw_muxed_v_21_cfg_reg_t;

  typedef struct packed {
    logic [1:0]  q;
  } astral_padframe_periph_config_reg2hw_muxed_v_21_mux_sel_reg_t;

  // Register -> HW type
  typedef struct packed {
    astral_padframe_periph_config_reg2hw_info_reg_t info; // [205:174]
    astral_padframe_periph_config_reg2hw_muxed_v_00_cfg_reg_t muxed_v_00_cfg; // [173:169]
    astral_padframe_periph_config_reg2hw_muxed_v_00_mux_sel_reg_t muxed_v_00_mux_sel; // [168:166]
    astral_padframe_periph_config_reg2hw_muxed_v_01_cfg_reg_t muxed_v_01_cfg; // [165:161]
    astral_padframe_periph_config_reg2hw_muxed_v_01_mux_sel_reg_t muxed_v_01_mux_sel; // [160:158]
    astral_padframe_periph_config_reg2hw_muxed_v_02_cfg_reg_t muxed_v_02_cfg; // [157:153]
    astral_padframe_periph_config_reg2hw_muxed_v_02_mux_sel_reg_t muxed_v_02_mux_sel; // [152:150]
    astral_padframe_periph_config_reg2hw_muxed_v_03_cfg_reg_t muxed_v_03_cfg; // [149:145]
    astral_padframe_periph_config_reg2hw_muxed_v_03_mux_sel_reg_t muxed_v_03_mux_sel; // [144:142]
    astral_padframe_periph_config_reg2hw_muxed_v_04_cfg_reg_t muxed_v_04_cfg; // [141:137]
    astral_padframe_periph_config_reg2hw_muxed_v_04_mux_sel_reg_t muxed_v_04_mux_sel; // [136:134]
    astral_padframe_periph_config_reg2hw_muxed_v_05_cfg_reg_t muxed_v_05_cfg; // [133:129]
    astral_padframe_periph_config_reg2hw_muxed_v_05_mux_sel_reg_t muxed_v_05_mux_sel; // [128:126]
    astral_padframe_periph_config_reg2hw_muxed_v_06_cfg_reg_t muxed_v_06_cfg; // [125:121]
    astral_padframe_periph_config_reg2hw_muxed_v_06_mux_sel_reg_t muxed_v_06_mux_sel; // [120:119]
    astral_padframe_periph_config_reg2hw_muxed_v_07_cfg_reg_t muxed_v_07_cfg; // [118:114]
    astral_padframe_periph_config_reg2hw_muxed_v_07_mux_sel_reg_t muxed_v_07_mux_sel; // [113:111]
    astral_padframe_periph_config_reg2hw_muxed_v_08_cfg_reg_t muxed_v_08_cfg; // [110:106]
    astral_padframe_periph_config_reg2hw_muxed_v_08_mux_sel_reg_t muxed_v_08_mux_sel; // [105:103]
    astral_padframe_periph_config_reg2hw_muxed_v_09_cfg_reg_t muxed_v_09_cfg; // [102:98]
    astral_padframe_periph_config_reg2hw_muxed_v_09_mux_sel_reg_t muxed_v_09_mux_sel; // [97:95]
    astral_padframe_periph_config_reg2hw_muxed_v_10_cfg_reg_t muxed_v_10_cfg; // [94:90]
    astral_padframe_periph_config_reg2hw_muxed_v_10_mux_sel_reg_t muxed_v_10_mux_sel; // [89:87]
    astral_padframe_periph_config_reg2hw_muxed_v_11_cfg_reg_t muxed_v_11_cfg; // [86:82]
    astral_padframe_periph_config_reg2hw_muxed_v_11_mux_sel_reg_t muxed_v_11_mux_sel; // [81:79]
    astral_padframe_periph_config_reg2hw_muxed_v_12_cfg_reg_t muxed_v_12_cfg; // [78:74]
    astral_padframe_periph_config_reg2hw_muxed_v_12_mux_sel_reg_t muxed_v_12_mux_sel; // [73:71]
    astral_padframe_periph_config_reg2hw_muxed_v_13_cfg_reg_t muxed_v_13_cfg; // [70:66]
    astral_padframe_periph_config_reg2hw_muxed_v_13_mux_sel_reg_t muxed_v_13_mux_sel; // [65:63]
    astral_padframe_periph_config_reg2hw_muxed_v_14_cfg_reg_t muxed_v_14_cfg; // [62:58]
    astral_padframe_periph_config_reg2hw_muxed_v_14_mux_sel_reg_t muxed_v_14_mux_sel; // [57:55]
    astral_padframe_periph_config_reg2hw_muxed_v_15_cfg_reg_t muxed_v_15_cfg; // [54:50]
    astral_padframe_periph_config_reg2hw_muxed_v_15_mux_sel_reg_t muxed_v_15_mux_sel; // [49:47]
    astral_padframe_periph_config_reg2hw_muxed_v_16_cfg_reg_t muxed_v_16_cfg; // [46:42]
    astral_padframe_periph_config_reg2hw_muxed_v_16_mux_sel_reg_t muxed_v_16_mux_sel; // [41:39]
    astral_padframe_periph_config_reg2hw_muxed_v_17_cfg_reg_t muxed_v_17_cfg; // [38:34]
    astral_padframe_periph_config_reg2hw_muxed_v_17_mux_sel_reg_t muxed_v_17_mux_sel; // [33:31]
    astral_padframe_periph_config_reg2hw_muxed_v_18_cfg_reg_t muxed_v_18_cfg; // [30:26]
    astral_padframe_periph_config_reg2hw_muxed_v_18_mux_sel_reg_t muxed_v_18_mux_sel; // [25:23]
    astral_padframe_periph_config_reg2hw_muxed_v_19_cfg_reg_t muxed_v_19_cfg; // [22:18]
    astral_padframe_periph_config_reg2hw_muxed_v_19_mux_sel_reg_t muxed_v_19_mux_sel; // [17:15]
    astral_padframe_periph_config_reg2hw_muxed_v_20_cfg_reg_t muxed_v_20_cfg; // [14:10]
    astral_padframe_periph_config_reg2hw_muxed_v_20_mux_sel_reg_t muxed_v_20_mux_sel; // [9:7]
    astral_padframe_periph_config_reg2hw_muxed_v_21_cfg_reg_t muxed_v_21_cfg; // [6:2]
    astral_padframe_periph_config_reg2hw_muxed_v_21_mux_sel_reg_t muxed_v_21_mux_sel; // [1:0]
  } astral_padframe_periph_config_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_INFO_OFFSET = 8'h 0;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_CFG_OFFSET = 8'h 4;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_MUX_SEL_OFFSET = 8'h 8;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_CFG_OFFSET = 8'h c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_MUX_SEL_OFFSET = 8'h 10;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_CFG_OFFSET = 8'h 14;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_MUX_SEL_OFFSET = 8'h 18;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_CFG_OFFSET = 8'h 1c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_MUX_SEL_OFFSET = 8'h 20;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_CFG_OFFSET = 8'h 24;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_MUX_SEL_OFFSET = 8'h 28;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_CFG_OFFSET = 8'h 2c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_MUX_SEL_OFFSET = 8'h 30;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_CFG_OFFSET = 8'h 34;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_MUX_SEL_OFFSET = 8'h 38;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_CFG_OFFSET = 8'h 3c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_MUX_SEL_OFFSET = 8'h 40;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_CFG_OFFSET = 8'h 44;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_MUX_SEL_OFFSET = 8'h 48;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_CFG_OFFSET = 8'h 4c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_MUX_SEL_OFFSET = 8'h 50;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_CFG_OFFSET = 8'h 54;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_MUX_SEL_OFFSET = 8'h 58;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_CFG_OFFSET = 8'h 5c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_MUX_SEL_OFFSET = 8'h 60;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_CFG_OFFSET = 8'h 64;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_MUX_SEL_OFFSET = 8'h 68;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_CFG_OFFSET = 8'h 6c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_MUX_SEL_OFFSET = 8'h 70;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_CFG_OFFSET = 8'h 74;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_MUX_SEL_OFFSET = 8'h 78;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_CFG_OFFSET = 8'h 7c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_MUX_SEL_OFFSET = 8'h 80;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_CFG_OFFSET = 8'h 84;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_MUX_SEL_OFFSET = 8'h 88;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_CFG_OFFSET = 8'h 8c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_MUX_SEL_OFFSET = 8'h 90;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_CFG_OFFSET = 8'h 94;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_MUX_SEL_OFFSET = 8'h 98;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_CFG_OFFSET = 8'h 9c;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_MUX_SEL_OFFSET = 8'h a0;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_CFG_OFFSET = 8'h a4;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_MUX_SEL_OFFSET = 8'h a8;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_CFG_OFFSET = 8'h ac;
  parameter logic [BlockAw-1:0] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_MUX_SEL_OFFSET = 8'h b0;

  // Register index
  typedef enum int {
    ASTRAL_PADFRAME_PERIPH_CONFIG_INFO,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_MUX_SEL,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_CFG,
    ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_MUX_SEL
  } astral_padframe_periph_config_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ASTRAL_PADFRAME_PERIPH_CONFIG_PERMIT [45] = '{
    4'b 1111, // index[ 0] ASTRAL_PADFRAME_PERIPH_CONFIG_INFO
    4'b 0001, // index[ 1] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_CFG
    4'b 0001, // index[ 2] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_00_MUX_SEL
    4'b 0001, // index[ 3] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_CFG
    4'b 0001, // index[ 4] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_01_MUX_SEL
    4'b 0001, // index[ 5] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_CFG
    4'b 0001, // index[ 6] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_02_MUX_SEL
    4'b 0001, // index[ 7] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_CFG
    4'b 0001, // index[ 8] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_03_MUX_SEL
    4'b 0001, // index[ 9] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_CFG
    4'b 0001, // index[10] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_04_MUX_SEL
    4'b 0001, // index[11] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_CFG
    4'b 0001, // index[12] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_05_MUX_SEL
    4'b 0001, // index[13] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_CFG
    4'b 0001, // index[14] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_06_MUX_SEL
    4'b 0001, // index[15] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_CFG
    4'b 0001, // index[16] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_07_MUX_SEL
    4'b 0001, // index[17] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_CFG
    4'b 0001, // index[18] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_08_MUX_SEL
    4'b 0001, // index[19] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_CFG
    4'b 0001, // index[20] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_09_MUX_SEL
    4'b 0001, // index[21] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_CFG
    4'b 0001, // index[22] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_10_MUX_SEL
    4'b 0001, // index[23] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_CFG
    4'b 0001, // index[24] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_11_MUX_SEL
    4'b 0001, // index[25] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_CFG
    4'b 0001, // index[26] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_12_MUX_SEL
    4'b 0001, // index[27] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_CFG
    4'b 0001, // index[28] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_13_MUX_SEL
    4'b 0001, // index[29] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_CFG
    4'b 0001, // index[30] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_14_MUX_SEL
    4'b 0001, // index[31] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_CFG
    4'b 0001, // index[32] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_15_MUX_SEL
    4'b 0001, // index[33] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_CFG
    4'b 0001, // index[34] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_16_MUX_SEL
    4'b 0001, // index[35] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_CFG
    4'b 0001, // index[36] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_17_MUX_SEL
    4'b 0001, // index[37] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_CFG
    4'b 0001, // index[38] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_18_MUX_SEL
    4'b 0001, // index[39] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_CFG
    4'b 0001, // index[40] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_19_MUX_SEL
    4'b 0001, // index[41] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_CFG
    4'b 0001, // index[42] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_20_MUX_SEL
    4'b 0001, // index[43] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_CFG
    4'b 0001  // index[44] ASTRAL_PADFRAME_PERIPH_CONFIG_MUXED_V_21_MUX_SEL
  };

endpackage

