
// File auto-generated by Padrick unknown
package pkg_astral_padframe;

  //Structs for botl

  //Static connections signals
   typedef struct packed {
      logic        fll_host_clk_o;
      logic        fll_secd_clk_o;
      logic        gpio_v_o_0;
      logic        gpio_v_o_1;
      logic        gpio_v_o_2;
      logic        gpio_v_o_3;
      logic        gpio_v_oen_i_0;
      logic        gpio_v_oen_i_1;
      logic        gpio_v_oen_i_2;
      logic        gpio_v_oen_i_3;
      logic        hyper_ck_no_0;
      logic        hyper_ck_no_1;
      logic        hyper_ck_o_0;
      logic        hyper_ck_o_1;
      logic        hyper_cs_no_0_0;
      logic        hyper_cs_no_0_1;
      logic        hyper_cs_no_1_0;
      logic        hyper_cs_no_1_1;
      logic        hyper_dq_o_0_0;
      logic        hyper_dq_o_0_1;
      logic        hyper_dq_o_0_2;
      logic        hyper_dq_o_0_3;
      logic        hyper_dq_o_0_4;
      logic        hyper_dq_o_0_5;
      logic        hyper_dq_o_0_6;
      logic        hyper_dq_o_0_7;
      logic        hyper_dq_o_1_0;
      logic        hyper_dq_o_1_1;
      logic        hyper_dq_o_1_2;
      logic        hyper_dq_o_1_3;
      logic        hyper_dq_o_1_4;
      logic        hyper_dq_o_1_5;
      logic        hyper_dq_o_1_6;
      logic        hyper_dq_o_1_7;
      logic        hyper_dq_oen_i_0;
      logic        hyper_dq_oen_i_1;
      logic        hyper_reset_no_0;
      logic        hyper_reset_no_1;
      logic        hyper_rwds_o_0;
      logic        hyper_rwds_o_1;
      logic        hyper_rwds_oen_i_0;
      logic        hyper_rwds_oen_i_1;
      logic        jtag_ot_tdo_o;
      logic        jtag_tdo_o;
      logic        ot_uart_tx_o;
      logic        spih_csb_o_1;
      logic        spih_ot_csb_o;
      logic        spih_ot_sck_o;
      logic        spih_ot_sd_o_0;
      logic        spih_ot_sd_o_1;
      logic        spih_ot_sd_o_2;
      logic        spih_ot_sd_o_3;
      logic        spih_ot_sd_oen_i_0;
      logic        spih_ot_sd_oen_i_1;
      logic        spih_ot_sd_oen_i_2;
      logic        spih_ot_sd_oen_i_3;
      logic        spih_sck_o;
      logic        spih_sd_o_0;
      logic        spih_sd_o_1;
      logic        spih_sd_o_2;
      logic        spih_sd_o_3;
      logic        spih_sd_oen_i_0;
      logic        spih_sd_oen_i_1;
      logic        spih_sd_oen_i_2;
      logic        spih_sd_oen_i_3;
      logic        uart_tx_o;
     } pad_domain_botl_static_connection_signals_soc2pad_t;

   typedef struct packed {
      logic        boot_mode_i_0;
      logic        boot_mode_i_1;
      logic        fll_bypass_i;
      logic        gpio_v_i_0;
      logic        gpio_v_i_1;
      logic        gpio_v_i_2;
      logic        gpio_v_i_3;
      logic        hyper_dq_i_0_0;
      logic        hyper_dq_i_0_1;
      logic        hyper_dq_i_0_2;
      logic        hyper_dq_i_0_3;
      logic        hyper_dq_i_0_4;
      logic        hyper_dq_i_0_5;
      logic        hyper_dq_i_0_6;
      logic        hyper_dq_i_0_7;
      logic        hyper_dq_i_1_0;
      logic        hyper_dq_i_1_1;
      logic        hyper_dq_i_1_2;
      logic        hyper_dq_i_1_3;
      logic        hyper_dq_i_1_4;
      logic        hyper_dq_i_1_5;
      logic        hyper_dq_i_1_6;
      logic        hyper_dq_i_1_7;
      logic        hyper_rwds_i_0;
      logic        hyper_rwds_i_1;
      logic        jtag_ot_tclk_i;
      logic        jtag_ot_tdi_i;
      logic        jtag_ot_tms_i;
      logic        jtag_ot_trst_ni;
      logic        jtag_tclk_i;
      logic        jtag_tdi_i;
      logic        jtag_tms_i;
      logic        jtag_trst_ni;
      logic        ot_boot_mode_i;
      logic        ot_uart_rx_i;
      logic        pwr_on_rst_ni;
      logic        ref_clk_i;
      logic        secure_boot_i;
      logic        spih_ot_sd_i_0;
      logic        spih_ot_sd_i_1;
      logic        spih_ot_sd_i_2;
      logic        spih_ot_sd_i_3;
      logic        spih_sd_i_0;
      logic        spih_sd_i_1;
      logic        spih_sd_i_2;
      logic        spih_sd_i_3;
      logic        uart_rx_i;
     } pad_domain_botl_static_connection_signals_pad2soc_t;


  //Toplevel structs

  typedef struct packed {
    pad_domain_botl_static_connection_signals_pad2soc_t botl;
  } static_connection_signals_pad2soc_t;

  typedef struct packed {
    pad_domain_botl_static_connection_signals_soc2pad_t botl;
  } static_connection_signals_soc2pad_t;



endpackage : pkg_astral_padframe
