// Copyright 2022 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Nicole Narr <narrn@student.ethz.ch>
// Christopher Reinwardt <creinwar@student.ethz.ch>
// Paul Scheffler <paulsc@iis.ee.ethz.ch>
// Robert Balas <balasr@iis.ee.ethz.ch>
// Alessandro Ottaviano <aottaviano@iis.ee.ethz.ch>
//
// This header provides information defined by hardware parameters, such as
// the address map. In the future, it should be generated automatically as
// part of the SoC generation process.

#ifndef __CAR_MEMORY_MAP_H
#define __CAR_MEMORY_MAP_H

#include "car_params.h"
#include "regs/safety_soc_ctrl.h"
#include "regs/soc_ctrl.h"
#include "regs/spatz_cluster_peripheral.h"

// Base addresses provided at link time
extern void *__base_l2;

// Main Islands and accelerators

// Cheshire
#define CHESHIRE_REGS_BASE_ADDR 0x03000000
#define CHESHIRE_NUM_INT_HARTS  CHESHIRE_REGS_BASE_ADDR + CHESHIRE_NUM_INT_HARTS_REG_OFFSET
#define CHESHIRE_HARTS_SYNC     CHESHIRE_REGS_BASE_ADDR + CHESHIRE_HARTS_SYNC_REG_OFFSET

// CVA6 HMR Unit
#define HMR_BASE_ADDR               0x0300B000
#define HMR_CORE_OFFS               0x100
#define HMR_DMR_OFFS                0x200
#define HMR_TMR_OFFS                0x300
#define HMR_CORE_INCREMENT          0x010
#define HMR_CORE_SLL                0x004
#define HMR_DMR_INCREMENT           0x010
#define HMR_DMR_SLL                 0x004
#define HMR_TMR_INCREMENT           0x010
#define HMR_TMR_SLL                 0x004

// Stack Pointer storage register
#define HMR_CORE_REGS_SP_STORE_REG_OFFSET 0x8
#define HMR_DMR_ENABLE_OFFS         0x0
#define HMR_DMR_CFG_REG_OFFS        0x4
#define HMR_DMR_CHECKPOINT_REG_OFFS 0x8
#define HMR_DMR_ENABLE              HMR_BASE_ADDR + HMR_DMR_OFFS + HMR_DMR_ENABLE_OFFS
#define HMR_DMR_CFG                 HMR_BASE_ADDR + HMR_DMR_OFFS + HMR_DMR_CFG_REG_OFFS
#define HMR_DMR_CHECKPOINT          HMR_BASE_ADDR + HMR_DMR_OFFS + HMR_DMR_CHECKPOINT_REG_OFFS

// L2 port 0
#define CAR_L2_SPM_PORT0_INTERLEAVED_BASE_ADDR(BASE) BASE
#define CAR_L2_SPM_PORT0_INTERLEAVED_END_ADDR(BASE)  (BASE + 0x20000)
#define CAR_L2_SPM_PORT0_CONTIGUOUS_BASE_ADDR(BASE)  BASE
#define CAR_L2_SPM_PORT0_CONTIGUOUS_END_ADDR(BASE)   (BASE + 0x20000)

// L2 port 1
#define CAR_L2_SPM_PORT1_INTERLEAVED_BASE_ADDR(BASE) BASE
#define CAR_L2_SPM_PORT1_INTERLEAVED_END_ADDR(BASE)  (BASE + 0x10000)
#define CAR_L2_SPM_PORT1_CONTIGUOUS_BASE_ADDR(BASE)  BASE
#define CAR_L2_SPM_PORT1_CONTIGUOUS_END_ADDR(BASE)   (BASE + 0x10000)

// Safety Island
#define CAR_SAFETY_ISLAND_SPM_BASE_ADDR(BASE) BASE
#define CAR_SAFETY_ISLAND_SPM_END_ADDR(BASE) (CAR_SAFETY_ISLAND_SPM_BASE_ADDR(BASE) + 0x20000)
#define CAR_SAFETY_ISLAND_PERIPHERALS_OFFSET 0x00200000
#define CAR_SAFETY_ISLAND_SOC_CTRL_OFFSET    0x00000000
#define CAR_SAFETY_ISLAND_ENTRY_POINT(BASE)        (CAR_SAFETY_ISLAND_SPM_BASE_ADDR(BASE) + 0x00010080)
#define CAR_SAFETY_ISLAND_SOC_CTRL_ADDR(BASE)      (CAR_SAFETY_ISLAND_SPM_BASE_ADDR(BASE) + CAR_SAFETY_ISLAND_PERIPHERALS_OFFSET + CAR_SAFETY_ISLAND_SOC_CTRL_OFFSET)

#define CAR_SAFETY_ISLAND_BOOTADDR_ADDR(BASE)      (CAR_SAFETY_ISLAND_SOC_CTRL_ADDR(BASE) + SAFETY_SOC_CTRL_BOOTADDR_REG_OFFSET)
#define CAR_SAFETY_ISLAND_FETCHEN_ADDR(BASE)       (CAR_SAFETY_ISLAND_SOC_CTRL_ADDR(BASE) + SAFETY_SOC_CTRL_FETCHEN_REG_OFFSET)
#define CAR_SAFETY_ISLAND_BOOTMODE_ADDR(BASE)      (CAR_SAFETY_ISLAND_SOC_CTRL_ADDR(BASE) + SAFETY_SOC_CTRL_BOOTMODE_REG_OFFSET)
#define CAR_SAFETY_ISLAND_CORESTATUS_ADDR(BASE)    (CAR_SAFETY_ISLAND_SOC_CTRL_ADDR(BASE) + SAFETY_SOC_CTRL_CORESTATUS_REG_OFFSET)

#define CAR_SAFETY_ISLAND_PERIPHS_BASE_ADDR(BASE) (CAR_SAFETY_ISLAND_SPM_BASE_ADDR(BASE) + CAR_SAFETY_ISLAND_PERIPHERALS_OFFSET)
#define CAR_SAFETY_ISLAND_PERIPHS_END_ADDR(BASE) (CAR_SAFETY_ISLAND_PERIPHS_BASE_ADDR(BASE) + 0x100000)

// Integer Cluster
#define CAR_INT_CLUSTER_SPM_BASE_ADDR(BASE) BASE
#define CAR_INT_CLUSTER_SPM_END_ADDR(BASE) (BASE + 0x20000)

#define CAR_INT_CLUSTER_PERIPH_OFFS           0x00200000
#define CAR_INT_CLUSTER_CTRL_UNIT_OFFS        0x00000000
#define CAR_INT_CLUSTER_CTRL_UNIT_RETURN_OFFS 0x100
#define CAR_INT_CLUSTER_RETURN_ADDR(BASE) (CAR_INT_CLUSTER_SPM_BASE_ADDR(BASE) + CAR_INT_CLUSTER_PERIPH_OFFS + CAR_INT_CLUSTER_CTRL_UNIT_OFFS + CAR_INT_CLUSTER_CTRL_UNIT_RETURN_OFFS)

#define CAR_INT_CLUSTER_BOOT_ADDR_OFFS 0x40
#define CAR_INT_CLUSTER_BOOT_ADDR_REG(BASE) (CAR_INT_CLUSTER_SPM_BASE_ADDR(BASE) + CAR_INT_CLUSTER_PERIPH_OFFS + CAR_INT_CLUSTER_CTRL_UNIT_OFFS + CAR_INT_CLUSTER_BOOT_ADDR_OFFS)

// Floating Point Spatz Cluster
#define CAR_FP_CLUSTER_SPM_BASE_ADDR(BASE) BASE
#define CAR_FP_CLUSTER_SPM_END_ADDR(BASE)  (BASE + 0x20000)

#define CAR_FP_CLUSTER_PERIPHS_BASE_ADDR(BASE) (BASE + 0x20000)
// #define CAR_FP_CLUSTER_PERIPHS_END_ADDR  unknown

// HyperRAM
#define CAR_HYPERRAM_BASE_ADDR 0x80400000
#define CAR_HYPERRAM_END_ADDR  0x80800000

// Peripheral devices
// from cheshire
#define CAR_BOOTROM_BASE_ADDR        0x000002000000
#define CAR_CLINT_BASE_ADDR          0x000002040000 // for both cores
#define CAR_IRQ_ROUTER_BASE_ADDR     0x000002080000
#define CAR_IRQ_AXI_REALM_BASE_ADDR  0x0000020c0000
#define CAR_CHESHIRE_CFG_BASE_ADDR   0x000003000000
#define CAR_LLC_CFG_BASE_ADDR        0x000003001000
#define CAR_CLIC_CFG_BASE_ADDR(id)   0x000008000000

// from carfield proper
#define CAR_PERIPHS_BASE_ADDR        0x20000000

#define CAR_ETHERNET_OFFSET          0x0000000
#define CAR_CAN_OFFSET               0x0001000
#define CAR_SYSTEM_TIMER_OFFSET      0x0004000
#define CAR_ADVANCED_TIMER_OFFSET    0x0005000
#define CAR_WATCHDOG_TIMER_OFFSET    0x0007000
#define CAR_HYPERBUS_CFG_OFFSET      0x0008000
#define CAR_STREAMER_CFG_OFFSET      0x0009000
#define CAR_STREAMER_APB_OFFSET      0x0011000
#define CAR_PAD_CFG_OFFSET           0x1000000

#define CAR_ETHERNET_BASE_ADDR       (CAR_PERIPHS_BASE_ADDR + CAR_ETHERNET_OFFSET)
#define CAR_CAN_BASE_ADDR            (CAR_PERIPHS_BASE_ADDR + CAR_CAN_OFFSET)
#define CAR_SYSTEM_TIMER_BASE_ADDR   (CAR_PERIPHS_BASE_ADDR + CAR_SYSTEM_TIMER_OFFSET)
#define CAR_ADVANCED_TIMER_BASE_ADDR (CAR_PERIPHS_BASE_ADDR + CAR_ADVANCED_TIMER_OFFSET)
#define CAR_WATCHDOG_TIMER_BASE_ADDR (CAR_PERIPHS_BASE_ADDR + CAR_WATCHDOG_TIMER_OFFSET)
#define CAR_HYPERBUS_CFG_BASE_ADDR   (CAR_PERIPHS_BASE_ADDR + CAR_HYPERBUS_CFG_OFFSET)
#define CAR_STREAMER_CFG_BASE_ADDR   (CAR_PERIPHS_BASE_ADDR + CAR_STREAMER_CFG_OFFSET)
#define CAR_STREAMER_APB_BASE_ADDR   (CAR_PERIPHS_BASE_ADDR + CAR_STREAMER_APB_OFFSET)
#define CAR_PAD_CFG_BASE_ADDR        (CAR_PERIPHS_BASE_ADDR + CAR_PAD_CFG_OFFSET)
#define CAR_SOC_CTRL_BASE_ADDR(BASE) BASE

// Mailbox
#define CAR_NUM_MAILBOXES            25
#define CAR_MBOX_BASE_ADDR           0x40000000

#define MBOX_INT_SND_STAT_OFFSET     0x00
#define MBOX_INT_SND_SET_OFFSET      0x04
#define MBOX_INT_SND_CLR_OFFSET      0x08
#define MBOX_INT_SND_EN_OFFSET       0x0C
#define MBOX_INT_RCV_STAT_OFFSET     0x40
#define MBOX_INT_RCV_SET_OFFSET      0x44
#define MBOX_INT_RCV_CLR_OFFSET      0x48
#define MBOX_INT_RCV_EN_OFFSET       0x4C
#define MBOX_LETTER0_OFFSET          0x80
#define MBOX_LETTER1_OFFSET          0x84

#define MBOX_CAR_INT_SND_STAT(id)		  (CAR_MBOX_BASE_ADDR + MBOX_INT_SND_STAT_OFFSET + (id*0x100))
#define MBOX_CAR_INT_SND_SET(id)          (CAR_MBOX_BASE_ADDR + MBOX_INT_SND_SET_OFFSET  + (id*0x100))
#define MBOX_CAR_INT_SND_CLR(id)          (CAR_MBOX_BASE_ADDR + MBOX_INT_SND_CLR_OFFSET  + (id*0x100))
#define MBOX_CAR_INT_SND_EN(id)           (CAR_MBOX_BASE_ADDR + MBOX_INT_SND_EN_OFFSET   + (id*0x100))
#define MBOX_CAR_INT_RCV_STAT(id)         (CAR_MBOX_BASE_ADDR + MBOX_INT_RCV_STAT_OFFSET + (id*0x100))
#define MBOX_CAR_INT_RCV_SET(id)          (CAR_MBOX_BASE_ADDR + MBOX_INT_RCV_SET_OFFSET  + (id*0x100))
#define MBOX_CAR_INT_RCV_CLR(id)          (CAR_MBOX_BASE_ADDR + MBOX_INT_RCV_CLR_OFFSET  + (id*0x100))
#define MBOX_CAR_INT_RCV_EN(id)           (CAR_MBOX_BASE_ADDR + MBOX_INT_RCV_EN_OFFSET   + (id*0x100))
#define MBOX_CAR_LETTER0(id)              (CAR_MBOX_BASE_ADDR + MBOX_LETTER0_OFFSET      + (id*0x100))
#define MBOX_CAR_LETTER1(id)              (CAR_MBOX_BASE_ADDR + MBOX_LETTER1_OFFSET      + (id*0x100))

//TCTM Streamer
#define TCTM_STREAMER_CFG_OFFS        0x0
#define TCTM_STREAMER_MAP_ROUTER_OFFS 0x0
#define TCTM_STREAMER_HPC_OFFS        0x80
#define TCTM_STREAMER_OBT_OFFS        0x100
#define TCTM_STREAMER_PTME_OFFS       0x180
#define TCTM_STREAMER_PTD_OFFS        0x200
#define TCTM_STREAMER_LLC_OFFS        0x280

#define TCTM_STREAMER_PTME_CFG_OFFS   0x000
#define TCTM_STREAMER_TM_PACKETS_OFFS 0x400
#define TCTM_STREAMER_TC_BUFFER_OFFS  0x800
#define TCTM_STREAMER_TX_BUFFER_OFFS  0xC00

#define TCTM_STREAMER_CFG_MAP_ROUTER_BASE CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_MAP_ROUTER_OFFS
#define TCTM_STREAMER_CFG_HPC_BASE        CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_HPC_OFFS
#define TCTM_STREAMER_CFG_OBT_BASE        CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_OBT_OFFS
#define TCTM_STREAMER_CFG_PTME_BASE       CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_PTME_OFFS
#define TCTM_STREAMER_CFG_PTD_BASE        CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_PTD_OFFS
#define TCTM_STREAMER_CFG_LLC_BASE        CAR_STREAMER_CFG_BASE_ADDR + TCTM_STREAMER_LLC_OFFS

#define TCTM_STREAMER_APB_PTME_CFG        CAR_STREAMER_APB_BASE_ADDR + TCTM_STREAMER_PTME_CFG_OFFS
#define TCTM_STREAMER_APB_TM_PACKET_BASE  CAR_STREAMER_APB_BASE_ADDR + TCTM_STREAMER_TM_PACKETS_OFFS
#define TCTM_STREAMER_APB_TC_BUFFER_BASE  CAR_STREAMER_APB_BASE_ADDR + TCTM_STREAMER_TC_BUFFER_OFFS
#define TCTM_STREAMER_APB_TX_BUFFER_BASE  CAR_STREAMER_APB_BASE_ADDR + TCTM_STREAMER_TX_BUFFER_OFFS

// FLL
#define FLL_ADDR_SPACE       0x20
#define FLL_HOST_ID          0x0
#define FLL_PERIPH_ID        0x1
#define FLL_ALT_ID           0x2
#define FLL_SECD_ID          0x3
#define FLL_RT_ID            0x4
#define FLL_BASE_ADDRESS(id) (fll + (id)*FLL_ADDR_SPACE)

#define FLL_STATUS_REG_I     0x00    
#define FLL_CONFIG_REG_I     0x08    
#define FLL_CONFIG_REG_II    0x10    
#define FLL_INTEGR_REG       0x18    

// Padframe
#define PADFRAME_BASE_ADDRESS padframe

#define PADFRAME_CONFIG_INFO 0x0

#define PADFRAME_CONFIG_MUXED_V_00_CFG 0x4
#define PADFRAME_CONFIG_MUXED_V_01_CFG 0xc
#define PADFRAME_CONFIG_MUXED_V_02_CFG 0x14
#define PADFRAME_CONFIG_MUXED_V_03_CFG 0x1c
#define PADFRAME_CONFIG_MUXED_V_04_CFG 0x24
#define PADFRAME_CONFIG_MUXED_V_05_CFG 0x2c
#define PADFRAME_CONFIG_MUXED_V_06_CFG 0x34
#define PADFRAME_CONFIG_MUXED_V_07_CFG 0x3c
#define PADFRAME_CONFIG_MUXED_V_08_CFG 0x44
#define PADFRAME_CONFIG_MUXED_V_09_CFG 0x4c
#define PADFRAME_CONFIG_MUXED_V_10_CFG 0x54
#define PADFRAME_CONFIG_MUXED_V_11_CFG 0x5c
#define PADFRAME_CONFIG_MUXED_V_12_CFG 0x64
#define PADFRAME_CONFIG_MUXED_V_13_CFG 0x6c
#define PADFRAME_CONFIG_MUXED_V_14_CFG 0x74
#define PADFRAME_CONFIG_MUXED_V_15_CFG 0x7c
#define PADFRAME_CONFIG_MUXED_V_16_CFG 0x84
#define PADFRAME_CONFIG_MUXED_V_17_CFG 0x8c
#define PADFRAME_CONFIG_MUXED_H_00_CFG 0x94
#define PADFRAME_CONFIG_MUXED_H_01_CFG 0x9c
#define PADFRAME_CONFIG_MUXED_H_02_CFG 0xa4
#define PADFRAME_CONFIG_MUXED_H_03_CFG 0xac

#define PADFRAME_CONFIG_MUXED_V_00_MUX_SEL 0x8
#define PADFRAME_CONFIG_MUXED_V_01_MUX_SEL 0x10
#define PADFRAME_CONFIG_MUXED_V_02_MUX_SEL 0x18
#define PADFRAME_CONFIG_MUXED_V_03_MUX_SEL 0x20
#define PADFRAME_CONFIG_MUXED_V_04_MUX_SEL 0x28
#define PADFRAME_CONFIG_MUXED_V_05_MUX_SEL 0x30
#define PADFRAME_CONFIG_MUXED_V_06_MUX_SEL 0x38
#define PADFRAME_CONFIG_MUXED_V_07_MUX_SEL 0x40
#define PADFRAME_CONFIG_MUXED_V_08_MUX_SEL 0x48
#define PADFRAME_CONFIG_MUXED_V_09_MUX_SEL 0x50
#define PADFRAME_CONFIG_MUXED_V_10_MUX_SEL 0x58
#define PADFRAME_CONFIG_MUXED_V_11_MUX_SEL 0x60
#define PADFRAME_CONFIG_MUXED_V_12_MUX_SEL 0x68
#define PADFRAME_CONFIG_MUXED_V_13_MUX_SEL 0x70
#define PADFRAME_CONFIG_MUXED_V_14_MUX_SEL 0x78
#define PADFRAME_CONFIG_MUXED_V_15_MUX_SEL 0x80
#define PADFRAME_CONFIG_MUXED_V_16_MUX_SEL 0x88
#define PADFRAME_CONFIG_MUXED_V_17_MUX_SEL 0x90
#define PADFRAME_CONFIG_MUXED_H_00_MUX_SEL 0x98
#define PADFRAME_CONFIG_MUXED_H_01_MUX_SEL 0xa0
#define PADFRAME_CONFIG_MUXED_H_02_MUX_SEL 0xa8
#define PADFRAME_CONFIG_MUXED_H_03_MUX_SEL 0xb0

#define PADFRAME_MUXED_V_00_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_00_SEL_CAN_RX                0x1
#define PADFRAME_MUXED_V_00_SEL_GPIO_IO_V_0           0x2
#define PADFRAME_MUXED_V_00_SEL_I2C_SDA               0x3
#define PADFRAME_MUXED_V_00_SEL_SPI_SCK               0x4
#define PADFRAME_MUXED_V_00_SEL_SPI_OT_SCK            0x5
#define PADFRAME_MUXED_V_01_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_01_SEL_CAN_TX                0x1
#define PADFRAME_MUXED_V_01_SEL_GPIO_IO_V_1           0x2
#define PADFRAME_MUXED_V_01_SEL_I2C_SCL               0x3
#define PADFRAME_MUXED_V_01_SEL_SPI_CSB_0             0x4
#define PADFRAME_MUXED_V_01_SEL_SPI_OT_CSB            0x5
#define PADFRAME_MUXED_V_02_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_02_SEL_GPIO_IO_V_2           0x1
#define PADFRAME_MUXED_V_02_SEL_SPI_CSB_1             0x2
#define PADFRAME_MUXED_V_02_SEL_SPI_OT_SD_0           0x3
#define PADFRAME_MUXED_V_03_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_03_SEL_GPIO_IO_V_3           0x1
#define PADFRAME_MUXED_V_03_SEL_SPI_SD_0              0x2
#define PADFRAME_MUXED_V_03_SEL_SPI_OT_SD_1           0x3
#define PADFRAME_MUXED_V_04_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_04_SEL_GPIO_IO_V_4           0x1
#define PADFRAME_MUXED_V_04_SEL_SERIAL_LINK_RCV_CLK_I 0x2
#define PADFRAME_MUXED_V_04_SEL_SPI_SD_1              0x3
#define PADFRAME_MUXED_V_04_SEL_SPI_OT_SD_2           0x4
#define PADFRAME_MUXED_V_05_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_05_SEL_GPIO_IO_V_5           0x1
#define PADFRAME_MUXED_V_05_SEL_SERIAL_LINK_I_0       0x2
#define PADFRAME_MUXED_V_05_SEL_SPI_SD_2              0x3
#define PADFRAME_MUXED_V_05_SEL_SPI_OT_SD_3           0x4
#define PADFRAME_MUXED_V_06_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_06_SEL_GPIO_IO_V_6           0x1
#define PADFRAME_MUXED_V_06_SEL_SERIAL_LINK_I_1       0x2
#define PADFRAME_MUXED_V_06_SEL_SPI_SD_3              0x3
#define PADFRAME_MUXED_V_07_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_07_SEL_ETHERNET_RXCK         0x1
#define PADFRAME_MUXED_V_07_SEL_GPIO_IO_V_7           0x2
#define PADFRAME_MUXED_V_07_SEL_PLL_IO_0              0x3
#define PADFRAME_MUXED_V_07_SEL_SERIAL_LINK_I_2       0x4
#define PADFRAME_MUXED_V_07_SEL_TC_ACTIVE             0x5
#define PADFRAME_MUXED_V_08_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_08_SEL_ETHERNET_RXCTL        0x1
#define PADFRAME_MUXED_V_08_SEL_GPIO_IO_V_8           0x2
#define PADFRAME_MUXED_V_08_SEL_PLL_IO_1              0x3
#define PADFRAME_MUXED_V_08_SEL_SERIAL_LINK_I_3       0x4
#define PADFRAME_MUXED_V_08_SEL_TC_CLK                0x5
#define PADFRAME_MUXED_V_09_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_09_SEL_ETHERNET_RXD_0        0x1
#define PADFRAME_MUXED_V_09_SEL_GPIO_IO_V_9           0x2
#define PADFRAME_MUXED_V_09_SEL_PLL_IO_2              0x3
#define PADFRAME_MUXED_V_09_SEL_SERIAL_LINK_I_4       0x4
#define PADFRAME_MUXED_V_09_SEL_TC_DATA               0x5
#define PADFRAME_MUXED_V_10_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_10_SEL_ETHERNET_RXD_1        0x1
#define PADFRAME_MUXED_V_10_SEL_GPIO_IO_V_10          0x2
#define PADFRAME_MUXED_V_10_SEL_PLL_IO_3              0x3
#define PADFRAME_MUXED_V_10_SEL_PTME_CLK              0x4
#define PADFRAME_MUXED_V_10_SEL_SERIAL_LINK_I_5       0x5
#define PADFRAME_MUXED_V_11_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_11_SEL_ETHERNET_RXD_2        0x1
#define PADFRAME_MUXED_V_11_SEL_GPIO_IO_V_11          0x2
#define PADFRAME_MUXED_V_11_SEL_PLL_IO_4              0x3
#define PADFRAME_MUXED_V_11_SEL_PTME_ENC              0x4
#define PADFRAME_MUXED_V_11_SEL_SERIAL_LINK_I_6       0x5
#define PADFRAME_MUXED_V_12_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_12_SEL_ETHERNET_RXD_3        0x1
#define PADFRAME_MUXED_V_12_SEL_GPIO_IO_V_12          0x2
#define PADFRAME_MUXED_V_12_SEL_PLL_IO_5              0x3
#define PADFRAME_MUXED_V_12_SEL_PTME_SYNC             0x4
#define PADFRAME_MUXED_V_12_SEL_SERIAL_LINK_I_7       0x5
#define PADFRAME_MUXED_V_13_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_13_SEL_ETHERNET_TXCK         0x1
#define PADFRAME_MUXED_V_13_SEL_GPIO_IO_V_13          0x2
#define PADFRAME_MUXED_V_13_SEL_PLL_IO_6              0x3
#define PADFRAME_MUXED_V_13_SEL_PTME_EXT_CLK          0x4
#define PADFRAME_MUXED_V_13_SEL_SERIAL_LINK_RCV_CLK_O 0x5
#define PADFRAME_MUXED_V_14_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_14_SEL_ETHERNET_TXCTL        0x1
#define PADFRAME_MUXED_V_14_SEL_GPIO_IO_V_14          0x2
#define PADFRAME_MUXED_V_14_SEL_HPC_ADDR_0            0x3
#define PADFRAME_MUXED_V_14_SEL_SERIAL_LINK_O_V_0     0x4
#define PADFRAME_MUXED_V_15_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_15_SEL_ETHERNET_TXD_0        0x1
#define PADFRAME_MUXED_V_15_SEL_GPIO_IO_V_15          0x2
#define PADFRAME_MUXED_V_15_SEL_HPC_ADDR_1            0x3
#define PADFRAME_MUXED_V_15_SEL_SERIAL_LINK_O_V_1     0x4
#define PADFRAME_MUXED_V_16_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_16_SEL_ETHERNET_TXD_1        0x1
#define PADFRAME_MUXED_V_16_SEL_GPIO_IO_V_16          0x2
#define PADFRAME_MUXED_V_16_SEL_HPC_ADDR_2            0x3
#define PADFRAME_MUXED_V_16_SEL_SERIAL_LINK_O_V_2     0x4
#define PADFRAME_MUXED_V_17_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_V_17_SEL_ETHERNET_TXD_2        0x1
#define PADFRAME_MUXED_V_17_SEL_GPIO_IO_V_17          0x2
#define PADFRAME_MUXED_V_17_SEL_HPC_CMD_EN            0x3
#define PADFRAME_MUXED_V_17_SEL_SERIAL_LINK_O_V_3     0x4
#define PADFRAME_MUXED_H_00_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_H_00_SEL_ETHERNET_TXD_3        0x1
#define PADFRAME_MUXED_H_00_SEL_GPIO_IO_H_0           0x2
#define PADFRAME_MUXED_H_00_SEL_HPC_SAMPLE            0x3
#define PADFRAME_MUXED_H_00_SEL_SERIAL_LINK_O_H_0     0x4
#define PADFRAME_MUXED_H_01_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_H_01_SEL_ETHERNET_MD           0x1
#define PADFRAME_MUXED_H_01_SEL_GPIO_IO_H_1           0x2
#define PADFRAME_MUXED_H_01_SEL_LLC_LINE_0            0x3
#define PADFRAME_MUXED_H_01_SEL_SERIAL_LINK_O_H_1     0x4
#define PADFRAME_MUXED_H_02_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_H_02_SEL_ETHERNET_MDC          0x1
#define PADFRAME_MUXED_H_02_SEL_GPIO_IO_H_2           0x2
#define PADFRAME_MUXED_H_02_SEL_LLC_LINE_1            0x3
#define PADFRAME_MUXED_H_02_SEL_SERIAL_LINK_O_H_2     0x4
#define PADFRAME_MUXED_H_03_SEL_DEFAULT               0x0
#define PADFRAME_MUXED_H_03_SEL_ETHERNET_RST_N        0x1
#define PADFRAME_MUXED_H_03_SEL_GPIO_IO_H_3           0x2
#define PADFRAME_MUXED_H_03_SEL_OBT_EXT_CLK           0x3
#define PADFRAME_MUXED_H_03_SEL_SERIAL_LINK_O_H_3     0x4

// Error codes
#define EHOSTDEXEC 1 // Execution error host domain
#define ESAFEDEXEC 2 // Execution error safe domain
#define EINTCLEXEC 3 // Execution error integer cluster
#define EFPCLEXEC  4 // Execution error floating point cluster

// Memory-mapped registers
#define CAR_INT_CLUSTER_FETCHEN_ADDR(BASE) (CAR_SOC_CTRL_BASE_ADDR(BASE) + CARFIELD_PULP_CLUSTER_FETCH_ENABLE_REG_OFFSET)
#define CAR_INT_CLUSTER_BOOTEN_ADDR(BASE)  (CAR_SOC_CTRL_BASE_ADDR(BASE) + CARFIELD_PULP_CLUSTER_BOOT_ENABLE_REG_OFFSET)
#define CAR_INT_CLUSTER_BUSY_ADDR(BASE)    (CAR_SOC_CTRL_BASE_ADDR(BASE) + CARFIELD_PULP_CLUSTER_BUSY_REG_OFFSET)
#define CAR_INT_CLUSTER_EOC_ADDR(BASE)     (CAR_SOC_CTRL_BASE_ADDR(BASE) + CARFIELD_PULP_CLUSTER_EOC_REG_OFFSET)

#endif /* __CAR_MEMORY_MAP_H */
