// File auto-generated by Padrick unknown

// Assignment Macros
// Assigns all members of port struct to another struct with same names but potentially different order

`define ASSIGN_PERIPH_SPI_PAD2SOC(load, driver) \
  assign load.spih_sd_0_i = driver.spih_sd_0_i; \
  assign load.spih_sd_1_i = driver.spih_sd_1_i; \
  assign load.spih_sd_2_i = driver.spih_sd_2_i; \
  assign load.spih_sd_3_i = driver.spih_sd_3_i; \

`define ASSIGN_PERIPH_SPI_SOC2PAD(load, driver) \
  assign load.spih_csb_0_o = driver.spih_csb_0_o; \
  assign load.spih_csb_0_pen_i = driver.spih_csb_0_pen_i; \
  assign load.spih_csb_0_psel_i = driver.spih_csb_0_psel_i; \
  assign load.spih_csb_1_o = driver.spih_csb_1_o; \
  assign load.spih_csb_1_pen_i = driver.spih_csb_1_pen_i; \
  assign load.spih_csb_1_psel_i = driver.spih_csb_1_psel_i; \
  assign load.spih_sck_o = driver.spih_sck_o; \
  assign load.spih_sck_pen_i = driver.spih_sck_pen_i; \
  assign load.spih_sck_psel_i = driver.spih_sck_psel_i; \
  assign load.spih_sd_0_o = driver.spih_sd_0_o; \
  assign load.spih_sd_0_oen_i = driver.spih_sd_0_oen_i; \
  assign load.spih_sd_0_pen_i = driver.spih_sd_0_pen_i; \
  assign load.spih_sd_0_psel_i = driver.spih_sd_0_psel_i; \
  assign load.spih_sd_1_o = driver.spih_sd_1_o; \
  assign load.spih_sd_1_oen_i = driver.spih_sd_1_oen_i; \
  assign load.spih_sd_1_pen_i = driver.spih_sd_1_pen_i; \
  assign load.spih_sd_1_psel_i = driver.spih_sd_1_psel_i; \
  assign load.spih_sd_2_o = driver.spih_sd_2_o; \
  assign load.spih_sd_2_oen_i = driver.spih_sd_2_oen_i; \
  assign load.spih_sd_2_pen_i = driver.spih_sd_2_pen_i; \
  assign load.spih_sd_2_psel_i = driver.spih_sd_2_psel_i; \
  assign load.spih_sd_3_o = driver.spih_sd_3_o; \
  assign load.spih_sd_3_oen_i = driver.spih_sd_3_oen_i; \
  assign load.spih_sd_3_pen_i = driver.spih_sd_3_pen_i; \
  assign load.spih_sd_3_psel_i = driver.spih_sd_3_psel_i; \

`define ASSIGN_PERIPH_ETHERNET_PAD2SOC(load, driver) \
  assign load.eth_md_i = driver.eth_md_i; \
  assign load.eth_rxck_i = driver.eth_rxck_i; \
  assign load.eth_rxctl_i = driver.eth_rxctl_i; \
  assign load.eth_rxd_0_i = driver.eth_rxd_0_i; \
  assign load.eth_rxd_1_i = driver.eth_rxd_1_i; \
  assign load.eth_rxd_2_i = driver.eth_rxd_2_i; \
  assign load.eth_rxd_3_i = driver.eth_rxd_3_i; \

`define ASSIGN_PERIPH_ETHERNET_SOC2PAD(load, driver) \
  assign load.eth_md_o = driver.eth_md_o; \
  assign load.eth_md_oen_i = driver.eth_md_oen_i; \
  assign load.eth_md_pen_i = driver.eth_md_pen_i; \
  assign load.eth_md_psel_i = driver.eth_md_psel_i; \
  assign load.eth_mdc_o = driver.eth_mdc_o; \
  assign load.eth_mdc_pen_i = driver.eth_mdc_pen_i; \
  assign load.eth_mdc_psel_i = driver.eth_mdc_psel_i; \
  assign load.eth_rst_n_pen_i = driver.eth_rst_n_pen_i; \
  assign load.eth_rst_n_psel_i = driver.eth_rst_n_psel_i; \
  assign load.eth_rst_no = driver.eth_rst_no; \
  assign load.eth_rxck_pen_i = driver.eth_rxck_pen_i; \
  assign load.eth_rxck_psel_i = driver.eth_rxck_psel_i; \
  assign load.eth_rxctl_pen_i = driver.eth_rxctl_pen_i; \
  assign load.eth_rxctl_psel_i = driver.eth_rxctl_psel_i; \
  assign load.eth_rxd_0_pen_i = driver.eth_rxd_0_pen_i; \
  assign load.eth_rxd_0_psel_i = driver.eth_rxd_0_psel_i; \
  assign load.eth_rxd_1_pen_i = driver.eth_rxd_1_pen_i; \
  assign load.eth_rxd_1_psel_i = driver.eth_rxd_1_psel_i; \
  assign load.eth_rxd_2_pen_i = driver.eth_rxd_2_pen_i; \
  assign load.eth_rxd_2_psel_i = driver.eth_rxd_2_psel_i; \
  assign load.eth_rxd_3_pen_i = driver.eth_rxd_3_pen_i; \
  assign load.eth_rxd_3_psel_i = driver.eth_rxd_3_psel_i; \
  assign load.eth_txck_o = driver.eth_txck_o; \
  assign load.eth_txck_pen_i = driver.eth_txck_pen_i; \
  assign load.eth_txck_psel_i = driver.eth_txck_psel_i; \
  assign load.eth_txctl_o = driver.eth_txctl_o; \
  assign load.eth_txctl_pen_i = driver.eth_txctl_pen_i; \
  assign load.eth_txctl_psel_i = driver.eth_txctl_psel_i; \
  assign load.eth_txd_0_o = driver.eth_txd_0_o; \
  assign load.eth_txd_0_pen_i = driver.eth_txd_0_pen_i; \
  assign load.eth_txd_0_psel_i = driver.eth_txd_0_psel_i; \
  assign load.eth_txd_1_o = driver.eth_txd_1_o; \
  assign load.eth_txd_1_pen_i = driver.eth_txd_1_pen_i; \
  assign load.eth_txd_1_psel_i = driver.eth_txd_1_psel_i; \
  assign load.eth_txd_2_o = driver.eth_txd_2_o; \
  assign load.eth_txd_2_pen_i = driver.eth_txd_2_pen_i; \
  assign load.eth_txd_2_psel_i = driver.eth_txd_2_psel_i; \
  assign load.eth_txd_3_o = driver.eth_txd_3_o; \
  assign load.eth_txd_3_pen_i = driver.eth_txd_3_pen_i; \
  assign load.eth_txd_3_psel_i = driver.eth_txd_3_psel_i; \

`define ASSIGN_PERIPH_CAN_PAD2SOC(load, driver) \
  assign load.can_rx_i = driver.can_rx_i; \

`define ASSIGN_PERIPH_CAN_SOC2PAD(load, driver) \
  assign load.can_rx_pen_i = driver.can_rx_pen_i; \
  assign load.can_rx_psel_i = driver.can_rx_psel_i; \
  assign load.can_tx_o = driver.can_tx_o; \
  assign load.can_tx_pen_i = driver.can_tx_pen_i; \
  assign load.can_tx_psel_i = driver.can_tx_psel_i; \

`define ASSIGN_PERIPH_SERIAL_LINK_PAD2SOC(load, driver) \
  assign load.slink_0_i = driver.slink_0_i; \
  assign load.slink_1_i = driver.slink_1_i; \
  assign load.slink_2_i = driver.slink_2_i; \
  assign load.slink_3_i = driver.slink_3_i; \
  assign load.slink_4_i = driver.slink_4_i; \
  assign load.slink_5_i = driver.slink_5_i; \
  assign load.slink_6_i = driver.slink_6_i; \
  assign load.slink_7_i = driver.slink_7_i; \
  assign load.slink_rcv_clk_i = driver.slink_rcv_clk_i; \

`define ASSIGN_PERIPH_SERIAL_LINK_SOC2PAD(load, driver) \
  assign load.slink_0_o = driver.slink_0_o; \
  assign load.slink_1_o = driver.slink_1_o; \
  assign load.slink_2_o = driver.slink_2_o; \
  assign load.slink_3_o = driver.slink_3_o; \
  assign load.slink_4_o = driver.slink_4_o; \
  assign load.slink_5_o = driver.slink_5_o; \
  assign load.slink_6_o = driver.slink_6_o; \
  assign load.slink_i_0_pen_i = driver.slink_i_0_pen_i; \
  assign load.slink_i_0_psel_i = driver.slink_i_0_psel_i; \
  assign load.slink_i_1_pen_i = driver.slink_i_1_pen_i; \
  assign load.slink_i_1_psel_i = driver.slink_i_1_psel_i; \
  assign load.slink_i_2_pen_i = driver.slink_i_2_pen_i; \
  assign load.slink_i_2_psel_i = driver.slink_i_2_psel_i; \
  assign load.slink_i_3_pen_i = driver.slink_i_3_pen_i; \
  assign load.slink_i_3_psel_i = driver.slink_i_3_psel_i; \
  assign load.slink_i_4_pen_i = driver.slink_i_4_pen_i; \
  assign load.slink_i_4_psel_i = driver.slink_i_4_psel_i; \
  assign load.slink_i_5_pen_i = driver.slink_i_5_pen_i; \
  assign load.slink_i_5_psel_i = driver.slink_i_5_psel_i; \
  assign load.slink_i_6_pen_i = driver.slink_i_6_pen_i; \
  assign load.slink_i_6_psel_i = driver.slink_i_6_psel_i; \
  assign load.slink_i_7_pen_i = driver.slink_i_7_pen_i; \
  assign load.slink_i_7_psel_i = driver.slink_i_7_psel_i; \
  assign load.slink_o_0_pen_i = driver.slink_o_0_pen_i; \
  assign load.slink_o_0_psel_i = driver.slink_o_0_psel_i; \
  assign load.slink_o_1_pen_i = driver.slink_o_1_pen_i; \
  assign load.slink_o_1_psel_i = driver.slink_o_1_psel_i; \
  assign load.slink_o_2_pen_i = driver.slink_o_2_pen_i; \
  assign load.slink_o_2_psel_i = driver.slink_o_2_psel_i; \
  assign load.slink_o_3_pen_i = driver.slink_o_3_pen_i; \
  assign load.slink_o_3_psel_i = driver.slink_o_3_psel_i; \
  assign load.slink_o_4_pen_i = driver.slink_o_4_pen_i; \
  assign load.slink_o_4_psel_i = driver.slink_o_4_psel_i; \
  assign load.slink_o_5_pen_i = driver.slink_o_5_pen_i; \
  assign load.slink_o_5_psel_i = driver.slink_o_5_psel_i; \
  assign load.slink_o_6_pen_i = driver.slink_o_6_pen_i; \
  assign load.slink_o_6_psel_i = driver.slink_o_6_psel_i; \
  assign load.slink_rcv_clk_i_pen_i = driver.slink_rcv_clk_i_pen_i; \
  assign load.slink_rcv_clk_i_psel_i = driver.slink_rcv_clk_i_psel_i; \
  assign load.slink_rcv_clk_o = driver.slink_rcv_clk_o; \
  assign load.slink_rcv_clk_o_pen_i = driver.slink_rcv_clk_o_pen_i; \
  assign load.slink_rcv_clk_o_psel_i = driver.slink_rcv_clk_o_psel_i; \

`define ASSIGN_PERIPH_I2C_PAD2SOC(load, driver) \
  assign load.i2c_scl_i = driver.i2c_scl_i; \
  assign load.i2c_sda_i = driver.i2c_sda_i; \

`define ASSIGN_PERIPH_I2C_SOC2PAD(load, driver) \
  assign load.i2c_scl_en_o = driver.i2c_scl_en_o; \
  assign load.i2c_scl_en_pen_i = driver.i2c_scl_en_pen_i; \
  assign load.i2c_scl_en_psel_i = driver.i2c_scl_en_psel_i; \
  assign load.i2c_scl_i_pen_i = driver.i2c_scl_i_pen_i; \
  assign load.i2c_scl_i_psel_i = driver.i2c_scl_i_psel_i; \
  assign load.i2c_scl_o = driver.i2c_scl_o; \
  assign load.i2c_scl_o_pen_i = driver.i2c_scl_o_pen_i; \
  assign load.i2c_scl_o_psel_i = driver.i2c_scl_o_psel_i; \
  assign load.i2c_sda_en_o = driver.i2c_sda_en_o; \
  assign load.i2c_sda_en_pen_i = driver.i2c_sda_en_pen_i; \
  assign load.i2c_sda_en_psel_i = driver.i2c_sda_en_psel_i; \
  assign load.i2c_sda_i_pen_i = driver.i2c_sda_i_pen_i; \
  assign load.i2c_sda_i_psel_i = driver.i2c_sda_i_psel_i; \
  assign load.i2c_sda_o = driver.i2c_sda_o; \
  assign load.i2c_sda_o_pen_i = driver.i2c_sda_o_pen_i; \
  assign load.i2c_sda_o_psel_i = driver.i2c_sda_o_psel_i; \

`define ASSIGN_PERIPH_TC_PAD2SOC(load, driver) \
  assign load.tc_active_i = driver.tc_active_i; \
  assign load.tc_clk_i = driver.tc_clk_i; \
  assign load.tc_data_i = driver.tc_data_i; \

`define ASSIGN_PERIPH_TC_SOC2PAD(load, driver) \
  assign load.tc_active_pen_i = driver.tc_active_pen_i; \
  assign load.tc_active_psel_i = driver.tc_active_psel_i; \
  assign load.tc_clk_pen_i = driver.tc_clk_pen_i; \
  assign load.tc_clk_psel_i = driver.tc_clk_psel_i; \
  assign load.tc_data_pen_i = driver.tc_data_pen_i; \
  assign load.tc_data_psel_i = driver.tc_data_psel_i; \

`define ASSIGN_PERIPH_PTME_PAD2SOC(load, driver) \
  assign load.ptme_ext_clk_i = driver.ptme_ext_clk_i; \

`define ASSIGN_PERIPH_PTME_SOC2PAD(load, driver) \
  assign load.ptme_clk_o = driver.ptme_clk_o; \
  assign load.ptme_clk_pen_i = driver.ptme_clk_pen_i; \
  assign load.ptme_clk_psel_i = driver.ptme_clk_psel_i; \
  assign load.ptme_enc_o = driver.ptme_enc_o; \
  assign load.ptme_enc_pen_i = driver.ptme_enc_pen_i; \
  assign load.ptme_enc_psel_i = driver.ptme_enc_psel_i; \
  assign load.ptme_ext_clk_pen_i = driver.ptme_ext_clk_pen_i; \
  assign load.ptme_ext_clk_psel_i = driver.ptme_ext_clk_psel_i; \
  assign load.ptme_sync_o = driver.ptme_sync_o; \
  assign load.ptme_sync_pen_i = driver.ptme_sync_pen_i; \
  assign load.ptme_sync_psel_i = driver.ptme_sync_psel_i; \


`define ASSIGN_PERIPH_HPC_SOC2PAD(load, driver) \
  assign load.hpc_addr_0_o = driver.hpc_addr_0_o; \
  assign load.hpc_addr_0_pen_i = driver.hpc_addr_0_pen_i; \
  assign load.hpc_addr_0_psel_i = driver.hpc_addr_0_psel_i; \
  assign load.hpc_addr_1_o = driver.hpc_addr_1_o; \
  assign load.hpc_addr_1_pen_i = driver.hpc_addr_1_pen_i; \
  assign load.hpc_addr_1_psel_i = driver.hpc_addr_1_psel_i; \
  assign load.hpc_addr_2_o = driver.hpc_addr_2_o; \
  assign load.hpc_addr_2_pen_i = driver.hpc_addr_2_pen_i; \
  assign load.hpc_addr_2_psel_i = driver.hpc_addr_2_psel_i; \
  assign load.hpc_cmd_en_o = driver.hpc_cmd_en_o; \
  assign load.hpc_cmd_en_pen_i = driver.hpc_cmd_en_pen_i; \
  assign load.hpc_cmd_en_psel_i = driver.hpc_cmd_en_psel_i; \
  assign load.hpc_sample_o = driver.hpc_sample_o; \
  assign load.hpc_sample_pen_i = driver.hpc_sample_pen_i; \
  assign load.hpc_sample_psel_i = driver.hpc_sample_psel_i; \


`define ASSIGN_PERIPH_LLC_SOC2PAD(load, driver) \
  assign load.llc_line_0_o = driver.llc_line_0_o; \
  assign load.llc_line_0_pen_i = driver.llc_line_0_pen_i; \
  assign load.llc_line_0_psel_i = driver.llc_line_0_psel_i; \
  assign load.llc_line_1_o = driver.llc_line_1_o; \
  assign load.llc_line_1_pen_i = driver.llc_line_1_pen_i; \
  assign load.llc_line_1_psel_i = driver.llc_line_1_psel_i; \

`define ASSIGN_PERIPH_OBT_PAD2SOC(load, driver) \
  assign load.obt_ext_clk_i = driver.obt_ext_clk_i; \

`define ASSIGN_PERIPH_OBT_SOC2PAD(load, driver) \
  assign load.obt_ext_clk_pen_i = driver.obt_ext_clk_pen_i; \
  assign load.obt_ext_clk_psel_i = driver.obt_ext_clk_psel_i; \

`define ASSIGN_PERIPH_SPI_OT_PAD2SOC(load, driver) \
  assign load.spih_ot_sd_0_i = driver.spih_ot_sd_0_i; \
  assign load.spih_ot_sd_1_i = driver.spih_ot_sd_1_i; \
  assign load.spih_ot_sd_2_i = driver.spih_ot_sd_2_i; \
  assign load.spih_ot_sd_3_i = driver.spih_ot_sd_3_i; \

`define ASSIGN_PERIPH_SPI_OT_SOC2PAD(load, driver) \
  assign load.spih_ot_csb_o = driver.spih_ot_csb_o; \
  assign load.spih_ot_csb_pen_i = driver.spih_ot_csb_pen_i; \
  assign load.spih_ot_csb_psel_i = driver.spih_ot_csb_psel_i; \
  assign load.spih_ot_sck_o = driver.spih_ot_sck_o; \
  assign load.spih_ot_sck_pen_i = driver.spih_ot_sck_pen_i; \
  assign load.spih_ot_sck_psel_i = driver.spih_ot_sck_psel_i; \
  assign load.spih_ot_sd_0_o = driver.spih_ot_sd_0_o; \
  assign load.spih_ot_sd_0_oen_i = driver.spih_ot_sd_0_oen_i; \
  assign load.spih_ot_sd_0_pen_i = driver.spih_ot_sd_0_pen_i; \
  assign load.spih_ot_sd_0_psel_i = driver.spih_ot_sd_0_psel_i; \
  assign load.spih_ot_sd_1_o = driver.spih_ot_sd_1_o; \
  assign load.spih_ot_sd_1_oen_i = driver.spih_ot_sd_1_oen_i; \
  assign load.spih_ot_sd_1_pen_i = driver.spih_ot_sd_1_pen_i; \
  assign load.spih_ot_sd_1_psel_i = driver.spih_ot_sd_1_psel_i; \
  assign load.spih_ot_sd_2_o = driver.spih_ot_sd_2_o; \
  assign load.spih_ot_sd_2_oen_i = driver.spih_ot_sd_2_oen_i; \
  assign load.spih_ot_sd_2_pen_i = driver.spih_ot_sd_2_pen_i; \
  assign load.spih_ot_sd_2_psel_i = driver.spih_ot_sd_2_psel_i; \
  assign load.spih_ot_sd_3_o = driver.spih_ot_sd_3_o; \
  assign load.spih_ot_sd_3_oen_i = driver.spih_ot_sd_3_oen_i; \
  assign load.spih_ot_sd_3_pen_i = driver.spih_ot_sd_3_pen_i; \
  assign load.spih_ot_sd_3_psel_i = driver.spih_ot_sd_3_psel_i; \

`define ASSIGN_PERIPH_PLL_PAD2SOC(load, driver) \
  assign load.pll_0_i = driver.pll_0_i; \
  assign load.pll_1_i = driver.pll_1_i; \
  assign load.pll_2_i = driver.pll_2_i; \
  assign load.pll_3_i = driver.pll_3_i; \
  assign load.pll_4_i = driver.pll_4_i; \
  assign load.pll_5_i = driver.pll_5_i; \
  assign load.pll_6_i = driver.pll_6_i; \

`define ASSIGN_PERIPH_PLL_SOC2PAD(load, driver) \
  assign load.pll_0_o = driver.pll_0_o; \
  assign load.pll_0_oen_i = driver.pll_0_oen_i; \
  assign load.pll_0_pen_i = driver.pll_0_pen_i; \
  assign load.pll_0_psel_i = driver.pll_0_psel_i; \
  assign load.pll_1_o = driver.pll_1_o; \
  assign load.pll_1_oen_i = driver.pll_1_oen_i; \
  assign load.pll_1_pen_i = driver.pll_1_pen_i; \
  assign load.pll_1_psel_i = driver.pll_1_psel_i; \
  assign load.pll_2_o = driver.pll_2_o; \
  assign load.pll_2_oen_i = driver.pll_2_oen_i; \
  assign load.pll_2_pen_i = driver.pll_2_pen_i; \
  assign load.pll_2_psel_i = driver.pll_2_psel_i; \
  assign load.pll_3_o = driver.pll_3_o; \
  assign load.pll_3_oen_i = driver.pll_3_oen_i; \
  assign load.pll_3_pen_i = driver.pll_3_pen_i; \
  assign load.pll_3_psel_i = driver.pll_3_psel_i; \
  assign load.pll_4_o = driver.pll_4_o; \
  assign load.pll_4_oen_i = driver.pll_4_oen_i; \
  assign load.pll_4_pen_i = driver.pll_4_pen_i; \
  assign load.pll_4_psel_i = driver.pll_4_psel_i; \
  assign load.pll_5_o = driver.pll_5_o; \
  assign load.pll_5_oen_i = driver.pll_5_oen_i; \
  assign load.pll_5_pen_i = driver.pll_5_pen_i; \
  assign load.pll_5_psel_i = driver.pll_5_psel_i; \
  assign load.pll_6_o = driver.pll_6_o; \
  assign load.pll_6_oen_i = driver.pll_6_oen_i; \
  assign load.pll_6_pen_i = driver.pll_6_pen_i; \
  assign load.pll_6_psel_i = driver.pll_6_psel_i; \

`define ASSIGN_PERIPH_GPIO_PAD2SOC(load, driver) \
  assign load.gpio_0_i = driver.gpio_0_i; \
  assign load.gpio_1_i = driver.gpio_1_i; \
  assign load.gpio_2_i = driver.gpio_2_i; \
  assign load.gpio_3_i = driver.gpio_3_i; \
  assign load.gpio_4_i = driver.gpio_4_i; \
  assign load.gpio_5_i = driver.gpio_5_i; \
  assign load.gpio_6_i = driver.gpio_6_i; \
  assign load.gpio_7_i = driver.gpio_7_i; \
  assign load.gpio_8_i = driver.gpio_8_i; \
  assign load.gpio_9_i = driver.gpio_9_i; \
  assign load.gpio_10_i = driver.gpio_10_i; \
  assign load.gpio_11_i = driver.gpio_11_i; \
  assign load.gpio_12_i = driver.gpio_12_i; \
  assign load.gpio_13_i = driver.gpio_13_i; \
  assign load.gpio_14_i = driver.gpio_14_i; \
  assign load.gpio_15_i = driver.gpio_15_i; \
  assign load.gpio_16_i = driver.gpio_16_i; \
  assign load.gpio_17_i = driver.gpio_17_i; \
  assign load.gpio_18_i = driver.gpio_18_i; \
  assign load.gpio_19_i = driver.gpio_19_i; \
  assign load.gpio_20_i = driver.gpio_20_i; \
  assign load.gpio_21_i = driver.gpio_21_i; \

`define ASSIGN_PERIPH_GPIO_SOC2PAD(load, driver) \
  assign load.gpio_0_o = driver.gpio_0_o; \
  assign load.gpio_0_oen_i = driver.gpio_0_oen_i; \
  assign load.gpio_0_pen_i = driver.gpio_0_pen_i; \
  assign load.gpio_0_psel_i = driver.gpio_0_psel_i; \
  assign load.gpio_1_o = driver.gpio_1_o; \
  assign load.gpio_1_oen_i = driver.gpio_1_oen_i; \
  assign load.gpio_1_pen_i = driver.gpio_1_pen_i; \
  assign load.gpio_1_psel_i = driver.gpio_1_psel_i; \
  assign load.gpio_2_o = driver.gpio_2_o; \
  assign load.gpio_2_oen_i = driver.gpio_2_oen_i; \
  assign load.gpio_2_pen_i = driver.gpio_2_pen_i; \
  assign load.gpio_2_psel_i = driver.gpio_2_psel_i; \
  assign load.gpio_3_o = driver.gpio_3_o; \
  assign load.gpio_3_oen_i = driver.gpio_3_oen_i; \
  assign load.gpio_3_pen_i = driver.gpio_3_pen_i; \
  assign load.gpio_3_psel_i = driver.gpio_3_psel_i; \
  assign load.gpio_4_o = driver.gpio_4_o; \
  assign load.gpio_4_oen_i = driver.gpio_4_oen_i; \
  assign load.gpio_4_pen_i = driver.gpio_4_pen_i; \
  assign load.gpio_4_psel_i = driver.gpio_4_psel_i; \
  assign load.gpio_5_o = driver.gpio_5_o; \
  assign load.gpio_5_oen_i = driver.gpio_5_oen_i; \
  assign load.gpio_5_pen_i = driver.gpio_5_pen_i; \
  assign load.gpio_5_psel_i = driver.gpio_5_psel_i; \
  assign load.gpio_6_o = driver.gpio_6_o; \
  assign load.gpio_6_oen_i = driver.gpio_6_oen_i; \
  assign load.gpio_6_pen_i = driver.gpio_6_pen_i; \
  assign load.gpio_6_psel_i = driver.gpio_6_psel_i; \
  assign load.gpio_7_o = driver.gpio_7_o; \
  assign load.gpio_7_oen_i = driver.gpio_7_oen_i; \
  assign load.gpio_7_pen_i = driver.gpio_7_pen_i; \
  assign load.gpio_7_psel_i = driver.gpio_7_psel_i; \
  assign load.gpio_8_o = driver.gpio_8_o; \
  assign load.gpio_8_oen_i = driver.gpio_8_oen_i; \
  assign load.gpio_8_pen_i = driver.gpio_8_pen_i; \
  assign load.gpio_8_psel_i = driver.gpio_8_psel_i; \
  assign load.gpio_9_o = driver.gpio_9_o; \
  assign load.gpio_9_oen_i = driver.gpio_9_oen_i; \
  assign load.gpio_9_pen_i = driver.gpio_9_pen_i; \
  assign load.gpio_9_psel_i = driver.gpio_9_psel_i; \
  assign load.gpio_10_o = driver.gpio_10_o; \
  assign load.gpio_10_oen_i = driver.gpio_10_oen_i; \
  assign load.gpio_10_pen_i = driver.gpio_10_pen_i; \
  assign load.gpio_10_psel_i = driver.gpio_10_psel_i; \
  assign load.gpio_11_o = driver.gpio_11_o; \
  assign load.gpio_11_oen_i = driver.gpio_11_oen_i; \
  assign load.gpio_11_pen_i = driver.gpio_11_pen_i; \
  assign load.gpio_11_psel_i = driver.gpio_11_psel_i; \
  assign load.gpio_12_o = driver.gpio_12_o; \
  assign load.gpio_12_oen_i = driver.gpio_12_oen_i; \
  assign load.gpio_12_pen_i = driver.gpio_12_pen_i; \
  assign load.gpio_12_psel_i = driver.gpio_12_psel_i; \
  assign load.gpio_13_o = driver.gpio_13_o; \
  assign load.gpio_13_oen_i = driver.gpio_13_oen_i; \
  assign load.gpio_13_pen_i = driver.gpio_13_pen_i; \
  assign load.gpio_13_psel_i = driver.gpio_13_psel_i; \
  assign load.gpio_14_o = driver.gpio_14_o; \
  assign load.gpio_14_oen_i = driver.gpio_14_oen_i; \
  assign load.gpio_14_pen_i = driver.gpio_14_pen_i; \
  assign load.gpio_14_psel_i = driver.gpio_14_psel_i; \
  assign load.gpio_15_o = driver.gpio_15_o; \
  assign load.gpio_15_oen_i = driver.gpio_15_oen_i; \
  assign load.gpio_15_pen_i = driver.gpio_15_pen_i; \
  assign load.gpio_15_psel_i = driver.gpio_15_psel_i; \
  assign load.gpio_16_o = driver.gpio_16_o; \
  assign load.gpio_16_oen_i = driver.gpio_16_oen_i; \
  assign load.gpio_16_pen_i = driver.gpio_16_pen_i; \
  assign load.gpio_16_psel_i = driver.gpio_16_psel_i; \
  assign load.gpio_17_o = driver.gpio_17_o; \
  assign load.gpio_17_oen_i = driver.gpio_17_oen_i; \
  assign load.gpio_17_pen_i = driver.gpio_17_pen_i; \
  assign load.gpio_17_psel_i = driver.gpio_17_psel_i; \
  assign load.gpio_18_o = driver.gpio_18_o; \
  assign load.gpio_18_oen_i = driver.gpio_18_oen_i; \
  assign load.gpio_18_pen_i = driver.gpio_18_pen_i; \
  assign load.gpio_18_psel_i = driver.gpio_18_psel_i; \
  assign load.gpio_19_o = driver.gpio_19_o; \
  assign load.gpio_19_oen_i = driver.gpio_19_oen_i; \
  assign load.gpio_19_pen_i = driver.gpio_19_pen_i; \
  assign load.gpio_19_psel_i = driver.gpio_19_psel_i; \
  assign load.gpio_20_o = driver.gpio_20_o; \
  assign load.gpio_20_oen_i = driver.gpio_20_oen_i; \
  assign load.gpio_20_pen_i = driver.gpio_20_pen_i; \
  assign load.gpio_20_psel_i = driver.gpio_20_psel_i; \
  assign load.gpio_21_o = driver.gpio_21_o; \
  assign load.gpio_21_oen_i = driver.gpio_21_oen_i; \
  assign load.gpio_21_pen_i = driver.gpio_21_pen_i; \
  assign load.gpio_21_psel_i = driver.gpio_21_psel_i; \


